Removed the drag and carry command while jailed
minipunch/usarealismrp-fxserver pull request #1059
Opened 2022-07-10 19:55 UTC by DatBoiWeep

2022-07-10 20:25 UTC, minipunch requested changes
see comments

2022-07-10 20:25 UTC, minipunch commented on resources/usa_drag/client.lua
> +					print('sent??')
plz remove debug prints when pushing live

2022-07-10 20:25 UTC, minipunch commented on resources/usa_drag/client.lua
> +AddEventHandler("death:toggleJailed", function(toggle)
If we're going to do it this way, can you at least rename the event from `death:toggleJailed` to something more generic so it makes more sense when used not in the `usa_death` script

Something like `usa:toggleJailedStatus`

2022-07-10 20:27 UTC, DatBoiWeep commented on resources/usa_drag/client.lua
> +					print('sent??')
Removed :)

2022-07-10 20:27 UTC, DatBoiWeep commented on resources/usa_drag/client.lua
> +AddEventHandler("death:toggleJailed", function(toggle)
On it boss

2022-07-11 01:35 UTC, minipunch approved these changes

2022-07-11 01:35 UTC, minipunch commented
hoping you ctrl + shift + f'd the whole repo to find all the scripts to rename all the events lul

2022-07-11 01:35 UTC, merged