Meth bug fix
minipunch/usarealismrp-fxserver pull request #1169
Opened 2022-08-25 06:13 UTC by DatBoiWeep

- When completing the cooking process for meth, it will now be dropped on the floor if the player's inventory is full.

2022-08-25 07:08 UTC, minipunch requested changes

2022-08-25 07:08 UTC, minipunch commented on resources/usa_meth/sv_meth.lua
> +	methProduced.coords = GetEntityCoords(GetPlayerPed(char.get("source")))
```suggestion
```

this overwrites the lines just before it, so it makes them pointless

so if u want the item to spawn in a random spot around the player and not just on the exact player coords every time, delete this line

and fyi it's the same exact thing as line 21, just called a bit differently

2022-08-25 07:14 UTC, DatBoiWeep commented on resources/usa_meth/sv_meth.lua
> +	methProduced.coords = GetEntityCoords(GetPlayerPed(char.get("source")))
oh LOL

2022-08-25 07:14 UTC, DatBoiWeep commented on resources/usa_meth/sv_meth.lua
> +	methProduced.coords = GetEntityCoords(GetPlayerPed(char.get("source")))
I will fix sir

2022-08-25 07:27 UTC, DatBoiWeep commented on resources/usa_meth/sv_meth.lua
> +	methProduced.coords = GetEntityCoords(GetPlayerPed(char.get("source")))
Removed it 😅

2022-08-27 03:45 UTC, minipunch approved these changes

2022-08-27 03:45 UTC, merged