feat(Oranges): Orange Collecting with UI
minipunch/usarealismrp-fxserver pull request #1200
Opened 2022-09-02 20:33 UTC by Crownapple

Today I present to you the collecting oranges, thanks to which you will be able to collect oranges on all orange trees on maps, and by the way there are 185 of them! It is possible to collect fruits on one tree only 1 time per restart for all players it is synchronized.

Multiple Sell / Buy Locations

2022-09-03 17:45 UTC, minipunch requested changes
What's the deal with the two resources being added, one with `_lib` appended?

And 2 of the files I've looked at are basically identical but with some little changes?

2022-09-03 18:06 UTC, Savage912-Official commented
> What's the deal with the two resources being added, one with `_lib` appended?
> 
> And 2 of the files I've looked at are basically identical but with some little changes?

It's the way the script came when it was bought but
Burevestnik_orangejob - Handles the orange picking / orange picking UI
Burevestnik_orangejob_lib - Handles the orange factory / orange factory UI

2022-09-03 18:26 UTC, minipunch commented
Love the mini game when picking and that seems to work p good

But the orange selling at the factory is very confusing at first

Can u try to add better notifications for that somehow?

The issue is the notifications show *behind* the selling UI so u can't see em

2022-09-03 18:27 UTC, minipunch commented
Also would be cool if we could make the orange tree blips go away after someone picks them (but the other thing is more important)

2022-09-03 18:27 UTC, minipunch requested changes
see comments

2022-09-03 18:32 UTC, Savage912-Official commented
> Love the mini game when picking and that seems to work p good
> 
> But the orange selling at the factory is very confusing at first
> 
> Can u try to add better notifications for that somehow?
> 
> The issue is the notifications show _behind_ the selling UI so u can't see em

Yeah i'll look into it. Also made the folder changed we talked about.

2022-09-04 18:09 UTC, minipunch commented
Niceeeeeeee @Savage912-Official 

Looks a lot better after being able to see the notifications now 👍 

Last thing before merging this is I think we should prob lower the payout just a bit

I got 360 for one tree, so like one litte section is 10k... and there's like 40-50k ish for all of them per restart for oranges

I guess it's not terrible

maybe I'll just lower a tad bit and push this 👍

2022-09-04 18:13 UTC, minipunch commented
Oh.. also one critical thing..

U gotta make sure player's can't use lua injectors (like eulen menu or what have u) to trigger the server events arbitrarily

U should

1) 'tokenize' the server event, see `salty_tokenizer` and how other scripts use the `securityToken` by sending it as an arg along with the triggered server event and it gets validated on the server sided script

2) add some server sided script logic/code that validates the event by making sure this player is actually supposed/allowed to be triggering it

2022-09-04 18:14 UTC, Savage912-Official commented
> Oh.. also one critical thing..
> 
> U gotta make sure player's can't use lua injectors (like eulen menu or what have u) to trigger the server events arbitrarily
> 
> U should
> 
> 1. 'tokenize' the server event, see `salty_tokenizer` and how other scripts use the `securityToken` by sending it as an arg along with the triggered server event and it gets validated on the server sided script
> 2. add some server sided script logic/code that validates the event by making sure this player is actually supposed/allowed to be triggering it

Sounds good! Will look into this in a bit

2022-09-04 18:23 UTC, minipunch commented
linking to #1190

2022-09-04 19:47 UTC, minipunch requested changes
- [ ] make my requested changes for the buying function
- [ ] also have to edit the ``_resource.lua` or `fxmanifest.lua` to include the init script for the tokenizer in server and client
- [ ] this is good for doing 1) but we should also do 2) from earlier because u can bypass tokens if u know how and have the rite tools

2022-09-04 19:47 UTC, minipunch commented on resources/[orange-picking]/Burevestnik_orangejob_lib/server.lua
> +    AddEventHandler('bur_orangejob_lib:buy', function(amount, price, securityToken)
Don't really need a security token for this function

Instead just make sure the price the client is sending is > 0, u can use `price = math.abs(price)` right at the start of the function

Otherwise the client could send a number like `-1000` for price and end up EARNING the money (since subtracting a negative number gives u addition)

2022-09-04 20:06 UTC, Savage912-Official commented on resources/[orange-picking]/Burevestnik_orangejob_lib/server.lua
> +    AddEventHandler('bur_orangejob_lib:buy', function(amount, price, securityToken)
Submitted all changes now just need to do "2) from earlier because u can bypass tokens if u know how and have the rite tools"

2022-09-05 00:31 UTC, Savage912-Official commented on resources/[orange-picking]/Burevestnik_orangejob_lib/server.lua
> +    AddEventHandler('bur_orangejob_lib:buy', function(amount, price, securityToken)
Everything from the list is completed

2022-09-05 03:22 UTC, minipunch commented on resources/[orange-picking]/Burevestnik_orangejob/config.lua
> +	{coords = vector3(-1844.6024, 2008.6498, 130.91185)},
I feel like these should be recorded somewhere already ? since it puts blips on the maps...

2022-09-05 03:56 UTC, minipunch approved these changes
Looks good otherwise, nice work

2022-09-05 03:57 UTC, merged