(Don't Push Yet) feat(Dumpsters): Ability to search dumpsters
minipunch/usarealismrp-fxserver pull request #1255
Opened 2022-09-14 02:58 UTC by Savage912-Official

**WAITING FOR MINI TO GIVE ME LIST OF ITEMS HE WANTS ADDED**

You can now search dumpsters for items.

2022-09-14 02:59 UTC, ChangyBoi commented
🥵

2022-09-14 02:59 UTC, DatBoiWeep commented
Like @minipunch would say "Sheesh papi"

2022-09-15 19:13 UTC, minipunch commented
🔥 

U know what would be good to find in dumpsters

HOTWIRING KITS since they r in high demand n somewhat low supply atm and u need em for boosting script

2022-09-15 20:08 UTC, Savage912-Official commented
> 🔥
> 
> U know what would be good to find in dumpsters
> 
> HOTWIRING KITS since they r in high demand n somewhat low supply atm and u need em for boosting script

Added it

2022-09-16 14:57 UTC, minipunch commented on resources/usa_dumpsters/client/client.lua
> +            if IsControlJustReleased(0, 54) then
Should make `54` into a named variable defined at the top so it can easily be changed later

2022-09-16 14:57 UTC, minipunch commented on resources/usa_dumpsters/client/client.lua
> +local dumpsters = {218085040, 666561306, -58485588, -206690185, 1511880420, 682791951}
What dumpsters work?

I am trying the ones near legion spawn but nothing happens

2022-09-16 15:00 UTC, minipunch commented on resources/usa_dumpsters/client/client.lua
> +                        exports.globals:notify("Dumpster already searched!")
It says this message after u 1) try to search a dumpster with a full inventory and 2) try to search again

So a player can't drop an item to free space and search again, can u fix this plz

2022-09-16 15:03 UTC, minipunch commented on resources/usa_dumpsters/client/client.lua
> +function dumpsterKeyPressed()
Can you add an animation and timer for this plz ?

2022-09-16 15:03 UTC, minipunch commented on resources/usa_dumpsters/client/client.lua
> +local dumpsters = {218085040, 666561306, -58485588, -206690185, 1511880420, 682791951}
Looks like it is just the big dumpsers? I guess that's fine for now

2022-09-16 15:08 UTC, Savage912-Official commented on resources/usa_dumpsters/client/client.lua
> +            if IsControlJustReleased(0, 54) then
Completed | Added to the config file

2022-09-16 15:08 UTC, minipunch requested changes
see comments

2022-09-16 15:15 UTC, Savage912-Official commented on resources/usa_dumpsters/client/client.lua
> +local dumpsters = {218085040, 666561306, -58485588, -206690185, 1511880420, 682791951}
Dumpsters that work:

[Dumpster 1](https://gtahash.ru/files/bins/prop_dumpster_01a.jpg)
[Dumpster 2](https://gtahash.ru/files/bins/prop_dumpster_02a.jpg)
[Dumpster 3](https://gtahash.ru/files/bins/prop_dumpster_02b.jpg)
[Dumpster 4](https://gtahash.ru/files/bins/prop_dumpster_3a.jpg)
[Dumpster 5](https://gtahash.ru/files/bins/prop_dumpster_4a.jpg)
[Dumpster 6](https://gtahash.ru/files/bins/prop_dumpster_4b.jpg)

2022-09-16 15:21 UTC, Savage912-Official commented on resources/usa_dumpsters/client/client.lua
> +local dumpsters = {218085040, 666561306, -58485588, -206690185, 1511880420, 682791951}
We can easily add some more though just let me know which ones.

2022-09-16 15:21 UTC, Savage912-Official commented on resources/usa_dumpsters/client/client.lua
> +function dumpsterKeyPressed()
Will work on it

2022-09-16 17:29 UTC, Savage912-Official commented on resources/usa_dumpsters/client/client.lua
> +function dumpsterKeyPressed()
Completed

2022-09-16 17:29 UTC, Savage912-Official commented on resources/usa_dumpsters/client/client.lua
> +                        exports.globals:notify("Dumpster already searched!")
Completed it will now drop the item on the ground if inventory is full.

2022-09-17 01:44 UTC, minipunch commented
- [ ] did u make sure the cooldown works for the dumpsters ?
- [ ] it looks like it's not synced between players, so one person can search it and then someone else can also search it

2022-09-17 01:48 UTC, minipunch requested changes

2022-09-17 01:48 UTC, minipunch commented on resources/usa_dumpsters/server/server.lua
> +        TriggerClientEvent('usa_dumpsters:server:startDumpsterTimer', id, object)
R u sure cooldown works?

Because the logic looks weird / like it won't work

And here u r triggering a client event that doesn't exist lol ?

2022-09-17 02:29 UTC, Savage912-Official commented on resources/usa_dumpsters/server/server.lua
> +        TriggerClientEvent('usa_dumpsters:server:startDumpsterTimer', id, object)
Yeah the creator apparently didn't finish it or some shit lol, Working on a fix now.

2022-09-17 02:34 UTC, Savage912-Official commented on resources/usa_dumpsters/server/server.lua
> +        TriggerClientEvent('usa_dumpsters:server:startDumpsterTimer', id, object)
Fixed!

2022-09-17 02:54 UTC, minipunch requested changes

2022-09-17 02:54 UTC, minipunch commented on resources/usa_dumpsters/client/client.lua
> +    for i = 1, #searched do
Should change it to `for i = #searched, 1, -1 do` to iterate backwards

Because that way if u remove an element mid loop it won't break mess up the order

2022-09-17 02:54 UTC, minipunch commented on resources/usa_dumpsters/server/server.lua
> +        if timer == 0 then
Should change to `<= 0` just in case

2022-09-17 02:54 UTC, minipunch commented on resources/usa_dumpsters/server/server.lua
> +        Wait(1000)
Also should use `os.time()` as it is more accurate p sure, but if u aren't sure how to do that this is prob ok for now at least

2022-09-17 02:54 UTC, minipunch commented on resources/usa_dumpsters/client/client.lua
> +    for i = 1, #searched do
```suggestion
    for i = #searched, 1, -1 do
```

2022-09-17 02:54 UTC, minipunch commented on resources/usa_dumpsters/server/server.lua
> +        if timer == 0 then
```suggestion
        if timer <= 0 then
```

2022-09-17 02:56 UTC, minipunch approved these changes

2022-09-17 02:56 UTC, merged