Armored Trucks
minipunch/usarealismrp-fxserver pull request #1301
Opened 2022-09-22 12:12 UTC by DatBoiWeep

**Armored Truck Attacks**
- Criminals now have an extra addition to attack armored trucks. Random hacking locations will be placed along with random truck spawn locations for criminals to hit.
- A large red circle will be placed for where the players will have to search for the armored truck

**To Do**
- [ ] Add more spawn locations
- [ ] Add more hacking locations
- [ ] Hints from dealers or peds of where hackable terminals are
- [ ] More stuff... maybe... :)

**Previews**
SoonTM

2022-09-24 20:31 UTC, minipunch commented
How does one get this piece of paper

and then I assume u just go to the terminal coords it tells you about and press a button to try to hack it, then there will be a button on the truck to place the sticky? Then u just take the money when it goes off ?

And u say there is a 1 hr cooldown for this?

Maybe u can show me in a VC so it's easier

2022-09-25 10:49 UTC, minipunch commented
- [ ] add paper to dumpsters
- [ ] put laptop into boosting shop for s coin

2022-09-25 11:06 UTC, minipunch requested changes
see comment

2022-09-25 22:47 UTC, DatBoiWeep commented
> * [x]  add paper to dumpsters
> * [x]  put laptop into boosting shop for s coin
> * [x]  tell player to 'check their map for the large red circle after hacking' in the paper notification
> * [x]  tell player they need a bag on the paper too
> * [x]  test cooldown

Cooldown will remove truck after 1 hour, if not impounded. Terminals can not be used during the cooldown as well.

Also fixed floating ped for boosting in the process of testing the boosting store

2022-10-01 20:43 UTC, minipunch commented on resources/av-warehouse/config.lua
> +			[7] = { name = "Laptop", type = "misc",  quantity = 1,  legality = "legal", notStackable = true,  weight = 10,  objectModel = "imp_prop_impexp_tablet" }
Since this is like specific to the bank truck heist right now maybe we should name it like "Bank Laptop" or smth llike that as a hint for its purpose ?

2022-10-01 20:48 UTC, minipunch commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] Once you hack a terminal, you'll get an approximate location.")
Can you add another hint that says they need that laptop I commented about earlier too plz

2022-10-01 20:49 UTC, minipunch commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] You'll definitely need a bag to store the laptop and something... that goes boom...")
```suggestion
	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] You'll definitely need a bag to store the money and something... that goes boom...")
```
the bag is to store the money from the truck right??

2022-10-01 20:50 UTC, minipunch commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] Once you hack a terminal, you'll get an approximate location.")
```suggestion
	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] Once you hack a terminal with the laptop, you'll get an approximate location.")
```

2022-10-01 20:52 UTC, minipunch commented on resources/core_rob_truck/client/functions.lua
> +	local CasinoHint = "^0[^5Terminal At Risk^0] The upper exterior level of the Casino. The terminal is located [^9REDACTED^0]"
Can you add some description of what the terminal looks like so we know what to look for at least

2022-10-01 21:38 UTC, DatBoiWeep commented on resources/av-warehouse/config.lua
> +			[7] = { name = "Laptop", type = "misc",  quantity = 1,  legality = "legal", notStackable = true,  weight = 10,  objectModel = "imp_prop_impexp_tablet" }
Could probably change it to that

2022-10-01 21:39 UTC, DatBoiWeep commented on resources/av-warehouse/config.lua
> +			[7] = { name = "Laptop", type = "misc",  quantity = 1,  legality = "legal", notStackable = true,  weight = 10,  objectModel = "imp_prop_impexp_tablet" }
I was originally going to add more of a purpose to this laptop, but can definitely call it a `bank laptop` for now

2022-10-01 21:51 UTC, DatBoiWeep commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] You'll definitely need a bag to store the laptop and something... that goes boom...")
well no. They actually need a bag to even get started with the hack. But I can put both

2022-10-01 21:51 UTC, DatBoiWeep commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] You'll definitely need a bag to store the laptop and something... that goes boom...")
ITS FOR ROLEPLAY MINI

2022-10-01 21:57 UTC, DatBoiWeep commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] Once you hack a terminal, you'll get an approximate location.")
Updated

2022-10-01 21:57 UTC, DatBoiWeep commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] You'll definitely need a bag to store the laptop and something... that goes boom...")
Updated

2022-10-01 21:57 UTC, DatBoiWeep commented on resources/core_rob_truck/client/functions.lua
> +	TriggerEvent("chatMessage", '', {0,0,0}, "^0[^2Hint^0] Once you hack a terminal, you'll get an approximate location.")
Updated

2022-10-01 21:59 UTC, DatBoiWeep commented on resources/core_rob_truck/client/functions.lua
> +	local CasinoHint = "^0[^5Terminal At Risk^0] The upper exterior level of the Casino. The terminal is located [^9REDACTED^0]"
hmm. Perhaps

2022-10-01 22:05 UTC, DatBoiWeep commented on resources/core_rob_truck/client/functions.lua
> +	local CasinoHint = "^0[^5Terminal At Risk^0] The upper exterior level of the Casino. The terminal is located [^9REDACTED^0]"
Completed

2022-10-01 22:05 UTC, DatBoiWeep commented
SHE'S READY FOR REVIEW AGAIN

2022-10-02 17:13 UTC, minipunch approved these changes

2022-10-02 17:13 UTC, minipunch commented
🔥

2022-10-02 17:13 UTC, merged