Prevent Electric Cars from using NOS
minipunch/usarealismrp-fxserver pull request #1303
Opened 2022-09-22 20:56 UTC by Urbaniized

2022-09-22 23:38 UTC, minipunch approved these changes

2022-09-22 23:39 UTC, minipunch requested changes

2022-09-22 23:39 UTC, minipunch commented on resources/usa_nitro/client/utils.lua
> +  [GetHashKey('I8')] = true
No commas???

This means u didn't test 😡😡😡

2022-09-22 23:40 UTC, Urbaniized commented on resources/usa_nitro/client/utils.lua
> +  [GetHashKey('I8')] = true
uhhh... 

I actually did test and it gave no errors and the script worked fine xD

Let me add them

2022-09-23 00:38 UTC, minipunch approved these changes

2022-09-23 00:38 UTC, merged