fix(Anticheat): Firetruck Flag Fix
minipunch/usarealismrp-fxserver pull request #1354
Opened 2022-10-02 03:50 UTC by Savage912-Official

2022-10-02 17:15 UTC, minipunch commented
Gonna mark as a draft since not tested

2022-10-02 21:44 UTC, Savage912-Official commented
Tested and seems to be working as intended.

2022-10-03 00:34 UTC, minipunch requested changes

2022-10-03 00:34 UTC, minipunch commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +  local veh = GetVehiclePedIsIn(me, false)
Calling natives (like `GetVehiclePedIsIn`) is performance intensive, and doing it every other frame (i.e., `Wait(1)` in a while true loop) is not good for optimization

Let's only call it when we need it 

So move it down to like under the check on like 85 so it gets called less and only when required

2022-10-03 02:07 UTC, Savage912-Official commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +  local veh = GetVehiclePedIsIn(me, false)
Working on this now

2022-10-03 02:11 UTC, Savage912-Official commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +  local veh = GetVehiclePedIsIn(me, false)
Submitted change

2022-10-04 14:32 UTC, minipunch reviewed
Did u actually test to confirm this worked?

Cuz I am wondering if line 100 is actually the line being called when throwing the flag or if this will actually fix it since that alert is thrown in more than just the lines u changed

2022-10-04 14:33 UTC, minipunch commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +  local veh = GetVehiclePedIsIn(me, false)
Looks better nice

2022-10-06 00:18 UTC, minipunch approved these changes

2022-10-06 00:18 UTC, merged