Unconscious Rework
minipunch/usarealismrp-fxserver pull request #1358
Opened 2022-10-03 01:22 UTC by maxgestic

- If downed you are unable to speak local and on radio (your character will be "unconscious" depending on how many serious injuries you have
- Emergency Services are able to use /epi {id} to inject a downed player with epinephrine to allow them to speak for 5 minutes while in the downed state (if revived and the player dies again the epi resets and the player will have to be re-injected to be able to speak again)

2022-10-04 18:21 UTC, minipunch requested changes
Looks good but just check out my comments

2022-10-04 18:21 UTC, minipunch commented on resources/rp-radio/client.lua
> +        local isBroadcasting = IsControlPressed(0, radioConfig.Controls.Broadcast.Key) and not IsPlayerFreeAiming(PlayerId()) and GetLastInputMethod(0) and exports.usa_injury:isConscious(GetPlayerPed
Careful with calling exports in a while loop like this is being called now: exports are 'expensive' to call (I think due to it having to search for the function to use) so this will most def raise the cpu msec usage (seen via `resmon`)

U should double check resmon to confirm that is indeed the case

And a fix would be to 'cache' the desired export function here locally and use it instead

So something like:

```
local injuryScript = exports.usa_injury

-- then call it like this:
if injuryScript:isConscious(GetPlayerPed(-1)) then
```

2022-10-04 18:21 UTC, minipunch commented on resources/usa_death/client.lua
> +	if IsEntityDead(GetPlayerPed(-1)) then
```suggestion
	if IsEntityDead(PlayerPedId()) then
```
I think that is a cleaner way to get the cur ped handle

2022-10-04 18:21 UTC, minipunch commented on resources/usa_death/client.lua
> +				if not exports.usa_injury:isConscious(GetPlayerPed(-1)) then
if u used the cache method above make sure u change how u call this also

so it would become: ``if not injuryScript:isConscious(PlayerPedId()) then``

2022-10-04 18:21 UTC, minipunch commented on resources/usa_injury/__resource.lua
> +    "isConscious"
fyi in the future an alternative/easier way to define exports if u didn't already know is in some .lua file other than fxmanifest.lua or __resource.lua (can be the same file the func is defined in):

```
exports('exportNameHere', function()
 -- function code for inline function, u can also just pass the name of an already defined elsewhere function instead
end)
```

2022-10-04 18:21 UTC, minipunch commented on resources/usa_injury/cl_injury.lua
> +            Citizen.Wait(1000)
Should use `GetGameTimer()` for measuring time instead of `Wait()` since wait varies based on the client's current FPS, so it might take longer and might take shorter whereas GetGameTimer is always accurate

2022-10-04 18:21 UTC, minipunch commented on resources/usa_injury/cl_injury.lua
> +            Citizen.Wait(1000)
U can see lots of other scripts use it if u need an example

2022-10-04 18:21 UTC, minipunch commented on resources/usa_injury/cl_injury.lua
> +            Citizen.Wait(1000)
Also what's with the double while loop lol, might be able to get rid of that also maybe if u use the above method

2022-10-04 20:52 UTC, maxgestic commented on resources/rp-radio/client.lua
> +        local isBroadcasting = IsControlPressed(0, radioConfig.Controls.Broadcast.Key) and not IsPlayerFreeAiming(PlayerId()) and GetLastInputMethod(0) and exports.usa_injury:isConscious(GetPlayerPed
Done

2022-10-04 20:53 UTC, maxgestic commented on resources/usa_injury/__resource.lua
> +    "isConscious"
Fair

2022-10-04 21:41 UTC, maxgestic commented on resources/usa_injury/cl_injury.lua
> +            Citizen.Wait(1000)
Done

2022-10-06 00:02 UTC, minipunch approved these changes

2022-10-06 00:02 UTC, merged