Reduced slots
minipunch/usarealismrp-fxserver pull request #1363
Opened 2022-10-04 16:39 UTC by Khajit71

Reduced the slots from 150 to 100 | Would look better when the server has like 70/100 rather than 70/150. Better for new players, makes the server look more full, and more appealing.

**COULDN'T TEST BECAUSE MY PC WOULD IMPLODE IF I WERE TO RUN A SERVER WITH 100 SLOTS!!!**

2022-10-09 20:02 UTC, Khajit71 commented
@minipunch

2022-10-16 20:56 UTC, minipunch commented
There is a max player count variable in the `connectqueue` resource that needs to be changed to match the new count also

2022-10-16 20:56 UTC, minipunch requested changes
see comment

2022-10-17 18:43 UTC, minipunch approved these changes

2022-10-17 18:43 UTC, merged