update(Injury): Allow staff & police inspect cmd
minipunch/usarealismrp-fxserver pull request #1398
Opened 2022-10-13 19:50 UTC by Savage912-Official

Added the ability for staff to use the inspect command rather than just police.

Requested by: @Khajit71

2022-10-15 16:46 UTC, minipunch commented
Why @Khajit71  ?

2022-10-16 16:32 UTC, Khajit71 commented
Because plenty of times we get /helps from ppl that their injuries got glitched and they need heal, and we need to double check with their injury log if injury's match. That, or if we need to check someone's injuries sometimes we don't have cop staff on @minipunch

2022-10-31 20:23 UTC, Savage912-Official commented
@minipunch

2022-11-01 07:59 UTC, minipunch requested changes

2022-11-01 07:59 UTC, minipunch commented on resources/usa_injury/sv_injury.lua
> +	if job == "corrections" or job == "sheriff" or job == "cop" or job == "ems" or group == "mod" or group == "admin" or group == "superadmin" or group == "owner" then
Looks like we lost 'doctor' from here ?

2022-11-01 14:19 UTC, Savage912-Official commented on resources/usa_injury/sv_injury.lua
> +	if job == "corrections" or job == "sheriff" or job == "cop" or job == "ems" or group == "mod" or group == "admin" or group == "superadmin" or group == "owner" then
Fixed

2022-11-01 18:23 UTC, minipunch approved these changes

2022-11-01 18:23 UTC, merged