update(Crafting): New Guns
minipunch/usarealismrp-fxserver pull request #1436
Opened 2022-10-24 18:06 UTC by Savage912-Official

2022-10-24 18:15 UTC, minipunch requested changes

2022-10-24 18:15 UTC, minipunch commented on resources/[inferno-collection]/inferno-weapons/client.lua
> +	"WEAPON_DBSHOTGUN",
we don't use this script anymore FYI so no need to update it anymore in the future

2022-10-24 18:15 UTC, minipunch commented on resources/usa-crafting/config.lua
> +Config.DEFAULT_CRAFT_DURATION_SECONDS = 1 * 10
lol let's not forget to undo our debug stuff in the future please 😂

2022-10-24 18:15 UTC, minipunch commented on resources/usa-crafting/config.lua
> +Config.MAX_FAIL_CHANCE = 0.10 -- max (and initial) chance to fail when crafting
same here

2022-10-24 18:17 UTC, Savage912-Official commented on resources/[inferno-collection]/inferno-weapons/client.lua
> +	"WEAPON_DBSHOTGUN",
Oh ok

2022-10-24 18:19 UTC, Savage912-Official commented on resources/usa-crafting/config.lua
> +Config.MAX_FAIL_CHANCE = 0.10 -- max (and initial) chance to fail when crafting
Fixed

2022-10-24 18:19 UTC, Savage912-Official commented on resources/usa-crafting/config.lua
> +Config.DEFAULT_CRAFT_DURATION_SECONDS = 1 * 10
Fixed

2022-10-25 06:39 UTC, minipunch approved these changes

2022-10-25 06:39 UTC, merged