Start resource
minipunch/usarealismrp-fxserver pull request #1450
Opened 2022-10-27 22:35 UTC by DatBoiWeep

- Added Anti Air supported by the US Air Force

Process
- Unathorized access entering the prison (or other restricted air access locations) will be prompted with a warning to flee
- After a few seconds, Prison will sound alarm and notify police of the aircraft
- Chance will occur for number of police on duty (100% chance of attack when 0 cops on duty)
- Cooldown will commence to prevent the heli from being repeatedly shot even when already down.
- Emergency Personnel are permitted in the Restricted Area.

2022-11-01 01:54 UTC, minipunch commented
Well first try nothing happening when I fly solo into the prison alone on the test server

Then after restarting the script it locked the prison down and I saw the 911 messages and warning to leave, but then an F8 error occured, prob cause of restarting it and needing to relog or smth?

2022-11-01 01:59 UTC, minipunch commented
Ok well second time trying after restarting the script and relogging I still got the same error:

![](https://i.imgur.com/SQ2LvbJ.png)

Also I noticed I only got warnings after I set my job to 'sheriff'

2022-11-01 02:00 UTC, minipunch requested changes

2022-11-01 02:00 UTC, minipunch commented on resources/nagodo_antiaircraft/scripts/client.lua
> +                                    if CopsOnDuty >= 1 then
this line is throwing the error: ![](https://i.imgur.com/SQ2LvbJ.png)

2022-11-03 21:21 UTC, DatBoiWeep commented on resources/nagodo_antiaircraft/scripts/client.lua
> +                                    if CopsOnDuty >= 1 then
This should be fixed now LOL

2022-11-04 01:33 UTC, minipunch commented
So it seemed to work better this time after spawning a chopper and flying in as a civ

It notified me and shot me down before I took off to leave

only issue is it threw this error in server console after shooting me: https://i.imgur.com/MHnhSiR.png

2022-11-04 01:36 UTC, minipunch commented
Also it seems like all u need is someone in another chopper behind u and it doesn't care about > 1 chopper ?

Is there like a cooldown or smth

2022-11-04 01:39 UTC, minipunch requested changes
see comment

2022-11-06 02:53 UTC, DatBoiWeep commented
> Also it seems like all u need is someone in another chopper behind u and it doesn't care about > 1 chopper ?
> 
> Is there like a cooldown or smth

There is a cooldown, but this error made the script stop because I never put coords in like a pepega. Should be pushed here in a bit for re-test

2022-11-06 20:19 UTC, minipunch commented
Lmao so does it always shoot u down even if it was an accident ??

Can't wait for people to accidentally get shot down lmao

2022-11-06 20:21 UTC, minipunch commented
Also we might wanna make it shoot u down a lil bit quicker

2022-11-06 20:27 UTC, minipunch requested changes

2022-11-06 20:27 UTC, minipunch commented on resources/nagodo_antiaircraft/scripts/client.lua
> +                            Wait(WaitAlarmTime)
Using `Wait()` is never reliable for time keeping cause it depends on the player's FPS

Should use `GetGameTimer()` instead, see other scripts for examples

2022-11-06 20:27 UTC, minipunch commented on resources/nagodo_antiaircraft/scripts/client.lua
> +local WaitAttackTime = 15000 -- 15 seconds
```suggestion
local WaitAttackTime = 10 * 1000
```

2022-11-06 22:40 UTC, minipunch requested changes

2022-11-06 22:40 UTC, minipunch commented on resources/nagodo_antiaircraft/scripts/client.lua
> +    local CopsOnDuty = TriggerServerCallback {
Code placed here only runs once when the thread on line 13 is created so this `CopsOnDuty` variable won't be accurate by the time a missile is fired

Should trigger this server callback once just before firing the missile if that is when u need to know how many cops are on instead

2022-11-06 22:59 UTC, minipunch commented
Pause I think I'm gonna work it around a little and clean it up a lil if possible

I don't really like the use of that `pause` variable in a loop like that lol

2022-11-06 23:32 UTC, minipunch approved these changes

2022-11-06 23:32 UTC, merged