Added Discord Log for modifying notes
minipunch/usarealismrp-fxserver pull request #1470
Opened 2022-10-31 23:01 UTC by maxgestic

Add convar as in DM i sent you mini

2022-11-01 00:40 UTC, minipunch requested changes

2022-11-01 00:40 UTC, minipunch commented on resources/usa-mdt/sv_mdt.lua
> +					name = 'Clocked out'
????

2022-11-01 00:40 UTC, minipunch commented on resources/usa-mdt/sv_mdt.lua
> +						name = "Modified Person",
```suggestion
						name = "Modified Note",
```

2022-11-01 00:40 UTC, minipunch commented on resources/usa-mdt/sv_mdt.lua
> +	local WEBHOOK_URL = GetConvar("mdt-webook", "")
Can you use the global export function for sending the discord message, see `[system]/globals` server side exports

2022-11-01 00:41 UTC, minipunch commented
Also this would be ideal to have in the MDT UI instead of in Discord

2022-11-01 20:13 UTC, maxgestic commented on resources/usa-mdt/sv_mdt.lua
> +					name = 'Clocked out'
My Bad, fixed this

2022-11-01 20:27 UTC, maxgestic commented on resources/usa-mdt/sv_mdt.lua
> +	local WEBHOOK_URL = GetConvar("mdt-webook", "")
IDK the export one looks kinda shit cos its a message rather than an embed
This is export:
![image](https://user-images.githubusercontent.com/3323241/199334201-ef49f3ac-1007-47ce-a4ef-6ace0669c289.png)
and this is the way i have it now:
![image](https://user-images.githubusercontent.com/3323241/199334261-a63a5175-fd0e-40bc-a2d9-3a1471743684.png)

2022-11-01 20:28 UTC, maxgestic commented
> Also this would be ideal to have in the MDT UI instead of in Discord, but for now I guess it's fine
> 
> what channel was this intended to send into and with what perms ?

Its the [mdt-log](https://discord.com/channels/297566457468944384/1036765933844316160) and permissions is all staff, all police command staff, judges and investigative units

2022-11-02 03:19 UTC, minipunch approved these changes

2022-11-02 03:19 UTC, merged