[Criminal Activity] Ability to NPC's Hostage
minipunch/usarealismrp-fxserver pull request #1485
Opened 2022-11-07 21:16 UTC by maxgestic

2022-11-08 02:34 UTC, minipunch requested changes

2022-11-08 02:34 UTC, minipunch commented on resources/robnpc/sv_robnpc.lua
> + --    if not exports['salty_tokenizer']:secureServerEvent(GetCurrentResourceName(), source, securityToken) then
rip

2022-11-08 02:34 UTC, minipunch commented on resources/robnpc/cl_robnpc.lua
> +                                    -- while securityToken == nil do
rip

2022-11-08 02:40 UTC, maxgestic commented on resources/robnpc/sv_robnpc.lua
> + --    if not exports['salty_tokenizer']:secureServerEvent(GetCurrentResourceName(), source, securityToken) then
fixed

2022-11-08 02:40 UTC, maxgestic commented on resources/robnpc/cl_robnpc.lua
> +                                    -- while securityToken == nil do
fixed

2022-11-09 04:57 UTC, minipunch approved these changes

2022-11-09 04:58 UTC, merged