feat(Casino): Aviator (Crash Game)
minipunch/usarealismrp-fxserver pull request #1498
Opened 2022-11-10 03:16 UTC by Savage912-Official

When the round starts, the game gives you a random number that can appear on the screen. You must cash out before you reach the random number given by the game by placing a bet. If you can cash out before you reach the number, you can see the money you have deposited and the money you have earned on the left. You can see how much the number went up in the previous rounds from the top.

In order to access this you must buy a Casino Dongle from a hardware store and have a laptop on you. When having both of these items use the Casino Dongle to access the game.

[Preview 1](https://cdn.discordapp.com/attachments/980523819246698496/980524111375765546/unknown.png)
[Preview 2](https://cdn.discordapp.com/attachments/980523819246698496/980524220142460988/unknown.png)

2022-11-27 23:17 UTC, minipunch requested changes

2022-11-27 23:17 UTC, minipunch commented on resources/oe-aviator/server/sv_aviator.lua
> +AddEventHandler('oe-aviator:addMoneyCallBack', function(data)
Gotta find a way to make this not exploitable

Security token is probably the laziest way but that would be the bare minimum for me to at least accept this PR

Other server sided checks are always preferable to the token method

2022-11-27 23:21 UTC, Savage912-Official commented on resources/oe-aviator/server/sv_aviator.lua
> +AddEventHandler('oe-aviator:addMoneyCallBack', function(data)
Alright, I'll get the security token and look into adding some other things in a bit.

2023-01-14 04:19 UTC, minipunch commented
Is this good to review?

Can u resolve the merge conflict if so

2023-01-20 15:14 UTC, Savage912-Official commented
> Is this good to review?
> 
> Can u resolve the merge conflict if so

Depends on if you think its secure enough to be pushed or if you think it can still be exploited.

2023-03-16 10:23 UTC, closed without merging