Tattoo v2
minipunch/usarealismrp-fxserver pull request #1513
Opened 2022-11-17 03:25 UTC by maxgestic

Changed Tattoos to use Fivem Appearance and other small changes

**MAKE SURE TO RUN "yarn build" in the fivem appearance folder after pulling!!!!!!**

Closes #1048

2022-11-17 06:17 UTC, minipunch commented on server.cfg
>  setr fivem-appearance:automaticFade 0
We might be able to enable this now

This was only disabled because the tattoos were disabled

I think it applies an automatic fade to certain haircuts or smth....

Not exactly sure which cuts to test with without looking more tho lol

2022-11-17 06:18 UTC, minipunch commented
Are tats that players have already going to be removed or will it transfer to this new system ?

2022-11-17 13:08 UTC, maxgestic commented on server.cfg
>  setr fivem-appearance:automaticFade 0
I'll have a lookie

2022-11-17 13:09 UTC, maxgestic commented
> Are tats that players have already going to be removed or will it transfer to this new system ?

They "should" stay...

2022-11-19 03:06 UTC, minipunch commented
see DM from me:

> "Can u make it so it removes their clothing, cause I can't see the tats I am trying on lol"

2022-11-19 03:06 UTC, minipunch requested changes
see comment

2022-11-19 03:08 UTC, minipunch commented
also just noticed I got this error at some point when trying this:

![](https://i.imgur.com/xfPCTlf.png)

2022-11-19 03:18 UTC, minipunch commented
Oh hold on I forgot about yarn build... let me try again..

2022-11-19 03:29 UTC, minipunch commented
> see DM from me:
> 
> > "Can u make it so it removes their clothing, cause I can't see the tats I am trying on lol"

This is fixed after running `yarn  build` in fivem-appearance but that F8 error still appears

2022-11-19 20:52 UTC, maxgestic commented
> also just noticed I got this error at some point when trying this:
> 
> ![](https://camo.githubusercontent.com/55dbaad698fd3951cf3e3851c45794228c286aa8919b03829ce1530df64ab2b5/68747470733a2f2f692e696d6775722e636f6d2f78665043546c662e706e67)

This is fixed by #[64a3c36](https://github.com/minipunch/usarealismrp-fxserver/pull/1513/commits/64a3c36200c18985cb49b4e33db14219fce69071)

2022-11-24 21:01 UTC, minipunch commented on resources/usa_tattooshop/sv_tattoos.lua
> +local TATTOO_FEE = 1000
```suggestion
local TATTOO_FEE = 2000
```

2022-11-25 20:28 UTC, minipunch approved these changes

2022-11-25 20:28 UTC, merged