Fixed Snowball Damage Mod Issues
minipunch/usarealismrp-fxserver pull request #1521
Opened 2022-11-19 21:28 UTC by maxgestic

Fixes #1517

2022-11-19 22:41 UTC, minipunch requested changes

2022-11-19 22:41 UTC, minipunch commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +        -- SetWeaponDamageModifier(currentSelected, whatItShouldBeModifier)
Can u make sure melee damage is still what it used to be (should be more than just 2-3 punches to down someone)

I had to use `SetWeaponDamageModifier` for that reason, since if I recall correctly when making this `SetPlayerWeaponDamageModifier` doesn't seem to work for melee like fists

2022-11-19 22:41 UTC, minipunch commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +        -- SetWeaponDamageModifier(currentSelected, whatItShouldBeModifier)
If it's broken with this change as I expect it to be can you just add `WEAPON_SNOWBALL` to the weapon modifier list and see if it works that way instead

2022-11-19 23:20 UTC, minipunch commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +        -- SetWeaponDamageModifier(currentSelected, whatItShouldBeModifier)
Also it looks like it conflicts the the thread defined below this one

That one sets `SetPlayerWeaponDamageModifier` to `1.0`

Yet yours is also setting it, but to something != `1.0`, so I would actually guess that this throws _anticheese flags too if u enable it

2022-11-19 23:23 UTC, maxgestic commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +        -- SetWeaponDamageModifier(currentSelected, whatItShouldBeModifier)
oh damn yea ok ill have a look probs just use this custom snowball https://github.com/CookayGaming/CustomSnowball

2022-11-20 00:41 UTC, minipunch commented on resources/usa_rp2/client/cl_weaponDamageModifier.lua
> +        -- SetWeaponDamageModifier(currentSelected, whatItShouldBeModifier)
Sounds good

2022-11-21 00:01 UTC, minipunch requested changes
see comment

2022-11-21 00:02 UTC, minipunch approved these changes

2022-11-21 00:02 UTC, merged