update(Evidence): Only show with Flashlight
minipunch/usarealismrp-fxserver pull request #1529
Opened 2022-11-23 13:12 UTC by Savage912-Official

Evidence will now only show if you have a flashlight in hand and aiming it.

Tested and works lol.

2022-11-24 20:34 UTC, minipunch requested changes

2022-11-24 20:34 UTC, minipunch commented on resources/usa_evidence/cl_evidence.lua
> +            TriggerServerEvent("evidence:loadNearbyEvidence", playerCoords)
why these changes / additions ?

2022-11-24 20:34 UTC, minipunch commented on resources/usa_evidence/cl_evidence.lua
> +            TriggerServerEvent("evidence:loadNearbyEvidence", playerCoords)
what was wrong with `mycoords`

2022-11-24 20:34 UTC, minipunch commented on resources/usa_evidence/cl_evidence.lua
> +			if IsPlayerFreeAiming(player) and GetSelectedPedWeapon(playerPed) == GetHashKey("WEAPON_FLASHLIGHT") then
native functions (i.e. `IsPlayerFreeAiming`) are CPU intensive to call so we should limit calling them as much as possible

therefore you should move this if statement check above the `for` loop since you don't need to check for every piece of evidence if they are free aiming.. only once before looping thru all the pieces of evidence..

2022-11-24 21:32 UTC, Savage912-Official commented on resources/usa_evidence/cl_evidence.lua
> +            TriggerServerEvent("evidence:loadNearbyEvidence", playerCoords)
No reason tbh and ill change back once github clone is done.

2022-11-24 21:32 UTC, Savage912-Official commented on resources/usa_evidence/cl_evidence.lua
> +			if IsPlayerFreeAiming(player) and GetSelectedPedWeapon(playerPed) == GetHashKey("WEAPON_FLASHLIGHT") then
I'll change once github clone is done.

2022-11-26 02:14 UTC, minipunch approved these changes

2022-11-26 02:14 UTC, merged