Fixed Train Dependency Issues
minipunch/usarealismrp-fxserver pull request #1532
Opened 2022-11-24 18:55 UTC by maxgestic

2022-11-24 20:29 UTC, minipunch requested changes

2022-11-24 20:29 UTC, minipunch commented on resources/[system]/globals/cl_global.lua
> +local isPassanger = false
Not a big fan of keeping this train state in the globals resource, seems very out of place

Instead of doing this can we first try what I suggested in dev chat instead?

2022-11-24 20:29 UTC, minipunch commented on resources/dpemotes/Client/Emote.lua
> +  if not exports.globals:checkIsPassanger() then
```suggestion
  if exports.usa_trains and exports.usa_trains.checkIsPassanger and not exports.usa_trains:checkIsPassanger() then
```

2022-11-24 20:29 UTC, minipunch commented on resources/dpemotes/Client/Emote.lua
> +  if not exports.globals:checkIsPassanger() then
like that, same applies to the other if statements

2022-11-25 03:53 UTC, minipunch requested changes

2022-11-25 03:53 UTC, minipunch commented on resources/dpemotes/Client/Emote.lua
> +  if not isPassanger then
Can we move all this into a local function... something like ``isPassenger` works fine probably

2022-11-25 03:53 UTC, minipunch commented on resources/usa_ammunition/client/cl_ammunition.lua
> +        if not isPassanger then
Same goes for here and other places that follow this same pattern

2022-11-25 03:53 UTC, minipunch commented on resources/usa_holster/client.lua
> +		        if not isPassanger then
Think this is the last place

2022-11-25 15:33 UTC, maxgestic commented
I had to do it the way its done here because exports.usa_trains returns a table even if the resource is not loaded.

2022-11-25 18:48 UTC, minipunch approved these changes

2022-11-25 18:48 UTC, merged