update(Prison): Prison Doors Require Cops
minipunch/usarealismrp-fxserver pull request #1551
Opened 2022-11-27 19:24 UTC by Savage912-Official

Prison doors can now only be lockpicked if there are 4 cops on duty. This is to stop people from escaping prison when there is no cops on duty.

2022-11-30 04:00 UTC, minipunch requested changes
Would be ideal if u could make this only apply to cell block doors

Cause right now it's ALL advanced lockpick-able doors that require 4 cops with the way u did it right, which might not be what we want if we add more in the future

2022-11-30 04:00 UTC, minipunch commented on resources/usa_doormanager/cl_doormanager.lua
> +            TriggerEvent('usa:notify', 'Seems there isn\'t enough cops around!')
```suggestion
            TriggerEvent('usa:notify', 'Lockpick failed')
```

2022-11-30 04:00 UTC, minipunch commented on resources/usa_doormanager/sv_doormanager.lua
> +RegisterServerCallback {eventName = 'usa_doormanager:getCops', eventCallback = function(source)
```suggestion
RegisterServerCallback {eventName = 'usa_doormanager:getNumCops', eventCallback = function(source)
```

2022-11-30 04:00 UTC, minipunch commented on resources/usa_doormanager/cl_doormanager.lua
> +            eventName = 'usa_doormanager:getCops',
```suggestion
            eventName = 'usa_doormanager:getNumCops',
```

2022-11-30 14:15 UTC, Savage912-Official commented
> Would be ideal if u could make this only apply to cell block doors
> 
> Cause right now it's ALL advanced lockpick-able doors that require 4 cops with the way u did it right, which might not be what we want if we add more in the future

Alright, ill work on it

2023-01-03 16:29 UTC, closed without merging

2023-01-03 16:29 UTC, Savage912-Official commented
Gonna come back to this later on no reason to have it open gonna make a new one when I have time for it.