update(Prison): Negative Time Fix
minipunch/usarealismrp-fxserver pull request #1571
Opened 2022-12-03 01:38 UTC by Savage912-Official

Prison jobs will only reduce your time if you have 5 or more months remaining on your sentence.

2022-12-04 02:54 UTC, minipunch requested changes

2022-12-04 02:54 UTC, minipunch commented on resources/usa_prison/jobs/janitor/sv_janitor.lua
> +        end
```suggestion
       char.set("jailTime", math.max(0, time))
```

2022-12-04 02:54 UTC, minipunch commented on resources/usa_prison/jobs/janitor/sv_janitor.lua
> +        end
That basically means it will always be >= 0

2022-12-04 03:21 UTC, Savage912-Official commented on resources/usa_prison/jobs/janitor/sv_janitor.lua
> +        end
Easy enough, didn't think of it that way. Learn new things everyday.

2022-12-04 21:07 UTC, minipunch commented on resources/usa_prison/jobs/janitor/sv_janitor.lua
> -        TriggerClientEvent("usa:notify", src, "Reduced Prison Time, New Time: " .. time)
Did you mean to remove this?

2022-12-04 21:34 UTC, Savage912-Official commented on resources/usa_prison/jobs/janitor/sv_janitor.lua
> -        TriggerClientEvent("usa:notify", src, "Reduced Prison Time, New Time: " .. time)
Nah it was removed when I did the other commit before I commited yours and didn't notice it.

2022-12-05 18:54 UTC, minipunch approved these changes

2022-12-05 18:54 UTC, minipunch approved these changes

2022-12-05 18:54 UTC, merged