[Carshop] Test Driving
minipunch/usarealismrp-fxserver pull request #1575
Opened 2022-12-04 02:26 UTC by maxgestic

Added ability to test drive any vehicles before buying them
Features:
- Adds 10 minute timer in which player can test drive and after will get warning to return car
- Adds 15 minute timer after which:
  - If there are not enough police, car will despawn
  - If there is enough police they will get a 911, and the ability to track the stolen vehicle using /trackveh [plate]
  - Police can also stop tracking vehicle with /endtrack
- Adds Return Point for vehicles that gets added to satnav when taking out test vehicle
- Strike System
  - If a car is kept for more than 15 minutes or is impounded or destroyed or otherwise lost player will get a strike
  - If a player has 3 strikes they will be banned from test driving and purchasing cars from all car dealerships for 30 real life days

2022-12-04 20:44 UTC, minipunch commented
I assume u just added some new button to the veh menu or something to activate it?

2022-12-04 21:02 UTC, maxgestic commented
Aye so when you go on a vehicle it now has Preview, Buy and Test Drive @minipunch

2022-12-04 21:04 UTC, maxgestic commented
Aye so when you go on a vehicle it now has Preview, Buy and Test Drive @minipunch

2022-12-08 08:57 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +				if diff > finalMinutes * 60 * 1000 then
Can u make the test drive time limit a constant at the top of the file so it's easily configurable please

2022-12-08 19:12 UTC, maxgestic commented on resources/usa_carshop/vehicle-shop_sv.lua
> +        db.getDocumentById("test-drive-strikes", char.get("_id"), function(doc)
There is no exports.essentialmode:getDocumentById(...)
and since that is the case no need to use exports for the update document cos i need to use exposeDBFunctions for getting the doc anyway

2022-12-08 19:15 UTC, maxgestic commented on resources/usa_carshop/vehicle-shop_sv.lua
> +		Citizen.Wait(5000)
Done

2022-12-08 19:16 UTC, maxgestic commented on resources/usa_carshop/vehicle-shop_sv.lua
> +				if diff > finalMinutes * 60 * 1000 then
Done [d9141f0](https://github.com/minipunch/usarealismrp-fxserver/pull/1575/commits/d9141f00140fc624ec1785f42a2fb8f70735410b)

2022-12-09 04:50 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +		while GetGameTimer() - lastCheck < 5000 do
Didn't realize `GetGameTimer()` worked on the server side lol.. that's why I recommended `os.time()`

2022-12-09 05:10 UTC, maxgestic commented on resources/usa_carshop/vehicle-shop_sv.lua
> +		while GetGameTimer() - lastCheck < 5000 do
I did indeed test it all works Good

2022-12-09 05:21 UTC, minipunch requested changes

2022-12-09 05:21 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +							TriggerClientEvent("usa:notify", v.source, "You did not return to the dealership, the emergency services have been called! "..strikes.."/3 strikes!")
Can u make this stuff show up in chat also please

Cuz the bottom left notifications go away too quickly and if u miss it ur out of luck

U can do it like this I think:

```suggestion
				TriggerClientEvent("usa:notify", v.source, "Your loaned car was destroyed or lost! "..strikes.."/3 strikes!", "^3INFO: ^0Your loaned car was destroyed or lost! "..strikes.."/3 strikes!")
```

2022-12-09 05:21 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +							TriggerClientEvent("usa:notify", v.source, "You did not return to the dealership, the emergency services have been called! "..strikes.."/3 strikes!")
Same with the other notifications

2022-12-10 21:39 UTC, minipunch commented
Nice

2022-12-10 22:29 UTC, maxgestic commented on resources/usa_carshop/vehicle-shop_sv.lua
> +						if numCops > 3 then
So crims don't just take like lambos and shit and steal them constantly when there is not enough cops to deal with it, 3 is a good amount for a chase

2022-12-11 20:24 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +				TriggerClientEvent("usa:notify", v.source, "Your loaned car was destroyed or lost! "..strikes.."/3 strikes!", "^3INFO: ^0Your loaned car was destroyed or lost! "..strikes.."/3 strikes!")
Hm ok, so basically that will just determine whether the script deletes the vehicle or not after the time limit then...

So in that case this help message is wrong then? wouldn't make sense to say the loaned car was destroyed or lost if they still have it in their possession right
```suggestion
local msg = "You failed to return the vehicle! Police have been called! " .. strikes .. "/3 strikes!"
				TriggerClientEvent("usa:notify", v.source, msg, "^3INFO: ^0" .. msg)
```

2022-12-11 20:25 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +						if numCops > 3 then
see comment below in that case

2022-12-11 21:37 UTC, maxgestic commented on resources/usa_carshop/vehicle-shop_sv.lua
> +				TriggerClientEvent("usa:notify", v.source, "Your loaned car was destroyed or lost! "..strikes.."/3 strikes!", "^3INFO: ^0Your loaned car was destroyed or lost! "..strikes.."/3 strikes!")
Yea that was weird i might have must pasted something wrong its fixed now with [c3a1dbe](https://github.com/minipunch/usarealismrp-fxserver/pull/1575/commits/c3a1dbe199e8360094f4de4cb59036e907bfa405)

2022-12-15 04:03 UTC, minipunch approved these changes

2022-12-15 04:03 UTC, merged