feat(Misc): Progress Bar Updates
minipunch/usarealismrp-fxserver pull request #1613
Opened 2022-12-14 17:57 UTC by Savage912-Official

Changed the current progressbar to a progressbar which is built into ox_lib. It is able to be cancelled and the cancel button can be changed in the fivem keybind settings.

Previews are in group chat.

Default cancel key is: BACKSPACE

2022-12-21 04:50 UTC, minipunch requested changes
Seems pretty good

But the nice thing about the other one is it tells you what key it is to cancel on screen while ur doing it

Can u add that to this please

2022-12-21 04:52 UTC, Savage912-Official commented
> Seems pretty good
> 
> But the nice thing about the other one is it tells you what key it is to cancel on screen while ur doing it
> 
> Can u add that to this please

Yep I’ll do it in the morning.

2022-12-21 17:54 UTC, minipunch commented on resources/ox_lib/resource/interface/client/progress.lua
> +            TriggerEvent('usa:showHelp', true, 'Cancel Progress Bar: ~INPUT_FRONTEND_RRIGHT~')
It looks like there is an extra R in the `INPUT_FRONTEND_RRIGHT` part ?

2022-12-23 01:17 UTC, minipunch commented on resources/ox_lib/resource/interface/client/progress.lua
> +            TriggerEvent('usa:showHelp', true, 'Cancel Progress Bar: ~INPUT_FRONTEND_RRIGHT~')
savage said it was how it was meant to be

2022-12-23 01:33 UTC, minipunch approved these changes

2022-12-23 01:34 UTC, merged