update(Crosshair): New Crosshair
minipunch/usarealismrp-fxserver pull request #1621
Opened 2022-12-16 00:35 UTC by Savage912-Official

This update adds a new crosshair and removes the old one so when you have your crosshair on someone it doesn't turn red anymore.

Requested by: @ChangyBoi

2022-12-17 22:38 UTC, minipunch commented on resources/usa-crosshair/client.lua
> +				SendNUIMessage("crosshairHide")
Is this necessary to call when `crosshairHide` is already being called above on line 26?

2022-12-17 22:53 UTC, Savage912-Official commented on resources/usa-crosshair/client.lua
> +				SendNUIMessage("crosshairHide")
I suppose not let me test it out before I change it though

2022-12-17 22:59 UTC, Savage912-Official commented on resources/usa-crosshair/client.lua
> +				SendNUIMessage("crosshairHide")
So, at this current moment it is needed because if you stop aiming the crosshair stays on the screen until you put your gun away. It's mainly being called on the line above to perform the checks for Config.Weapons.Reticle.

2022-12-17 23:01 UTC, Savage912-Official commented on resources/usa-crosshair/client.lua
> +				SendNUIMessage("crosshairHide")
I did remove the one right below for the if is ped armed check, since we only needed it for is player free aiming.

2022-12-17 23:32 UTC, minipunch commented on resources/usa-crosshair/client.lua
> +				SendNUIMessage("crosshairHide")
Hm ok

2022-12-17 23:33 UTC, minipunch requested changes

2022-12-17 23:33 UTC, minipunch commented on resources/usa-crosshair/client.lua
> +				SendNUIMessage("crosshairHide")
Also not a fan of calling `SendNUIMessage` on every frame as is done on line 53

We should only need to call that once to activate and once to deactivate instead of in a loop like that

2022-12-20 01:59 UTC, minipunch approved these changes

2022-12-20 01:59 UTC, merged