New Crafting Items
minipunch/usarealismrp-fxserver pull request #1624
Opened 2022-12-16 04:04 UTC by Zeeroqt

* New Crafting items *Tweaked Crafting Timer
*More useful stuff used for the community
*ADDED HOTWIRING KITS!!!!
*Armor now craftable 😱
----
Hope Yall enjoy

2022-12-21 10:45 UTC, Zeeroqt commented
When will this be pushed?

2022-12-23 01:36 UTC, minipunch commented on resources/usa-crafting/config.lua
> +                    weight = 15,
Why change this

2022-12-23 01:39 UTC, minipunch commented on resources/interaction-menu/ui/js/script.js
> +    "Fuse": "https://imgur.com/qNOnWZg.png",
How about using 'wire' instead of a 'fuse' item for these crafts

2022-12-23 01:44 UTC, minipunch requested changes

2022-12-23 01:44 UTC, minipunch commented on resources/usa-crafting/config.lua
> +                    type = "misc",
```suggestion
                    type = "weapon",
```
weapons need to have type = `weapon`

2022-12-23 01:44 UTC, minipunch commented on resources/usa-crafting/config.lua
> +                    type = "misc",
makes me wonder if u tested this?

2022-12-23 01:44 UTC, minipunch commented on resources/usa-crafting/config.lua
> +                { name = "Fabric", quantity = 8 },
```suggestion
                { name = "Kevlar", quantity = 8 },
```

2022-12-23 01:44 UTC, minipunch commented on resources/usa-crafting/config.lua
> +                { name = "tape", quantity = 6 }
"tape" ???

2022-12-23 01:44 UTC, minipunch commented on resources/usa-crafting/config.lua
> +                { name = "Fabric", quantity = 10 },
```suggestion
                { name = "Kevlar", quantity = 10 },
```

2022-12-23 01:44 UTC, minipunch commented on resources/usa-crafting/config.lua
> +Config.DEFAULT_CRAFT_DURATION_SECONDS = 5 * 60
```suggestion
Config.DEFAULT_CRAFT_DURATION_SECONDS = 8 * 60
```

2022-12-23 01:44 UTC, minipunch commented on resources/usa-crafting/config.lua
> +Config.MAX_FAIL_CHANCE = 0.55 -- max (and initial) chance to fail when crafting
```suggestion
Config.MAX_FAIL_CHANCE = 0.60 -- max (and initial) chance to fail when crafting
```

2022-12-23 02:04 UTC, Zeeroqt commented on resources/usa-crafting/config.lua
> +                    weight = 15,
i changed this due it being the most used weapon in the server and the inventory weight is really only 100

2022-12-23 02:04 UTC, Zeeroqt commented on resources/interaction-menu/ui/js/script.js
> +    "Fuse": "https://imgur.com/qNOnWZg.png",
👍

2022-12-23 02:05 UTC, Zeeroqt commented on resources/usa-crafting/config.lua
> +                    type = "misc",
i forgot to change this to weapon before i pushed it

2022-12-23 02:06 UTC, Zeeroqt commented on resources/usa-crafting/config.lua
> +Config.DEFAULT_CRAFT_DURATION_SECONDS = 5 * 60
8 minutes is honestly really long just for it to fail about 5 times just to get the item u want and i saw it in suggestions and figured to give a shot?

2022-12-23 02:06 UTC, Zeeroqt commented on resources/usa-crafting/config.lua
> +                { name = "tape", quantity = 6 }
yea its "crafting"  u have to some how manage to put together the items

2022-12-23 02:07 UTC, Zeeroqt commented on resources/usa-crafting/config.lua
> +                { name = "Fabric", quantity = 8 },
i like it

2022-12-26 21:00 UTC, minipunch commented on resources/usa-crafting/config.lua
> +                { name = "tape", quantity = 6 }
U gotta make sure capitalization is correct or it won't work as an item

2022-12-26 21:01 UTC, minipunch commented
Since we changed "fabric" to "kevlar" you need to also remove other references to "fabric" and replace them with "kevlar"

Like atm there is no way to get kevlar?

2022-12-26 21:02 UTC, minipunch commented
Just to be safe here and we don't miss anything I am going to close this PR and have you make separate PRs for each feature or addition

So 1 for crafting armor

1 for hotwiring kits

and whatever else... if u added it here, make a new PR for it separately

2022-12-26 21:02 UTC, closed without merging