Less Than Lethal Changes
minipunch/usarealismrp-fxserver pull request #1636
Opened 2022-12-20 06:04 UTC by maxgestic

- Added Beanbag Shotgun
- Added Effect to player if hit by less than lethals

2022-12-26 21:08 UTC, minipunch requested changes

2022-12-26 21:08 UTC, minipunch commented on resources/_dmgevents/cl_damageEvents.lua
> +            if weaponHash == GetHashKey("WEAPON_BEANBAGSHOTGUN") then
For the sake of optimizing can you instead of getting the hash keys for the weapon every time a damage event is triggered can you do it at the top of the file for example so it only runs once and then just use the value

P sure we have gone thru this on another PR before

2022-12-26 21:08 UTC, minipunch commented on resources/_dmgevents/cl_damageEvents.lua
> +            if weaponHash == GetHashKey("WEAPON_BEANBAGSHOTGUN") then
Throughout the file

2022-12-26 21:08 UTC, minipunch commented on resources/_dmgevents/cl_damageEvents.lua
> +                    Citizen.Wait(15000)
Again let's not rely on `Wait` for timing things on the client, use GetGameTimer() instead please

2023-01-07 23:48 UTC, maxgestic commented on resources/_dmgevents/cl_damageEvents.lua
> +            if weaponHash == GetHashKey("WEAPON_BEANBAGSHOTGUN") then
Fixed https://github.com/minipunch/usarealismrp-fxserver/pull/1636/commits/f459c0eaaafc8354bacdaa09513b98cb8e793c4f

2023-01-07 23:57 UTC, maxgestic commented on resources/_dmgevents/cl_damageEvents.lua
> +                    Citizen.Wait(15000)
Fixed https://github.com/minipunch/usarealismrp-fxserver/pull/1636/commits/94e50f6c5de8b95ea4a0d7238de9dff624dacc44

2023-01-14 22:12 UTC, minipunch approved these changes

2023-01-14 22:12 UTC, merged