Added ATM Robbing
minipunch/usarealismrp-fxserver pull request #1649
Opened 2022-12-21 23:52 UTC by maxgestic

Ability to Rob ATM's with a Drill and a Thermite

2022-12-26 21:24 UTC, minipunch commented on resources/banking/client.lua
> +    TriggerEvent("usa:notify", "You are not anywhere to use your Drill...")
```suggestion
    TriggerEvent("usa:notify", "Nothing to drill")
```

2022-12-26 21:47 UTC, minipunch requested changes

2022-12-26 21:47 UTC, minipunch commented on resources/banking/client.lua
> +      if GetGameTimer() - drilledAt > 180000 then -- 3 minutes to use thermite after which have to redrill
Instead of the 'magic numbers' can u define them as easily configurable named constants at the top or in a config file please, here something like `THERMITE_REDRILL_TIME_LIMIT_MINUTES`

2022-12-26 21:47 UTC, minipunch commented on resources/banking/client.lua
> +      if GetGameTimer() - drilledAt > 180000 then -- 3 minutes to use thermite after which have to redrill
Also why the 3 minute time limit to plant thermite in the first place?

2022-12-26 21:47 UTC, minipunch commented on resources/banking/server.lua
> +AddEventHandler("banking:pickupMoney", function(money)
Just created an infinite money exploit wit dis one lol

2022-12-26 21:47 UTC, minipunch commented on resources/banking/server.lua
> +AddEventHandler("banking:pickupMoney", function(money)
U should know this!! Don't ever trust values sent from a client when performing critical server sided logic like updating a player's money!

You should generate the random amount of money on the server sided script and not pass it from the client

Also some server sided validation logic to assert that someone arbitrarily calling it won't result in a similar exploit (i.e. making sure it only actually gives the person who triggered it money if they actually deserve it... here that could be like making sure they were near an atm when it blew up or smth like that)

2023-01-08 00:31 UTC, maxgestic commented on resources/banking/client.lua
> +      if GetGameTimer() - drilledAt > 180000 then -- 3 minutes to use thermite after which have to redrill
The time limit is there to prevent drilling a bunch of ATM's leaving them and then coming back later when the cops already responded to the calls and just plating the terhmite and getting the money with no cop response

2023-01-08 00:31 UTC, maxgestic commented on resources/banking/client.lua
> +      if GetGameTimer() - drilledAt > 180000 then -- 3 minutes to use thermite after which have to redrill
Fixed https://github.com/minipunch/usarealismrp-fxserver/pull/1649/commits/d902196469a39b7ab67241accd864fe3f16c29d3

2023-01-08 01:40 UTC, maxgestic commented on resources/banking/server.lua
> +AddEventHandler("banking:pickupMoney", function(money)
Dis now also fixed https://github.com/minipunch/usarealismrp-fxserver/pull/1649/commits/575c9528676e1a2da675f0793db656b81b5999c2

2023-01-14 22:18 UTC, minipunch commented on resources/banking/server.lua
> +    	if GetGameTimer() - robbedATMs[coords] < ATM_ROBBED_TIMEOUT_HOURS * 3600000 then
what is the * 3600000 about lol ?

2023-01-14 22:54 UTC, minipunch commented
okay hell yeah this is nice

last thing I think though is can we add a little animation for picking up the money

it can be the same one as planting thermite for now if u want

2023-01-15 02:16 UTC, maxgestic commented on resources/banking/server.lua
> +    	if GetGameTimer() - robbedATMs[coords] < ATM_ROBBED_TIMEOUT_HOURS * 3600000 then
Hours to Milliseconds

2023-01-15 02:16 UTC, maxgestic commented on resources/banking/server.lua
> +    	if GetGameTimer() - robbedATMs[coords] < ATM_ROBBED_TIMEOUT_HOURS * 3600000 then
![Screenshot_20230115-021621.png](https://user-images.githubusercontent.com/3323241/212519488-d35dd025-d70e-4302-8374-1752d3bb7310.png)

2023-01-16 18:00 UTC, maxgestic commented
Added Animation in https://github.com/minipunch/usarealismrp-fxserver/pull/1649/commits/dfa068e1b544fea1e3133fdbedb62bb5a50e113b

2023-01-25 03:32 UTC, minipunch approved these changes

2023-01-25 03:32 UTC, merged