Fixed sell price at dealership issue
minipunch/usarealismrp-fxserver pull request #1660
Opened 2022-12-25 22:50 UTC by DatBoiWeep

Fixed VIN scracthed vehicles selling at a different price from the stated return value

2022-12-26 03:31 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +	if currentPrice > 0 then -- If a price is set above 0 then use existing price
why > 0 here ?

2022-12-26 03:31 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +	if currentPrice > 0 then -- If a price is set above 0 then use existing price
Is there ever a case where a vehicle has <= 0 for its `.price` attribute?

2022-12-26 03:33 UTC, DatBoiWeep commented on resources/usa_carshop/vehicle-shop_sv.lua
> +	if currentPrice > 0 then -- If a price is set above 0 then use existing price
I put it there in case a car would ever have a value of nil for whatever reason, but I guess you do be right. Would be pointless

2022-12-26 03:41 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +	if currentPrice > 0 then -- If a price is set above 0 then use existing price
> I put it there in case a car would ever have a value of nil for whatever reason, but I guess you do be right. Would be pointless

Can we just do `if toSellVehicle.price then` then?

2022-12-26 03:42 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +	if currentPrice > 0 then -- If a price is set above 0 then use existing price
And why do some cars not have a .price attached to them in the first place?

2022-12-26 03:50 UTC, DatBoiWeep commented on resources/usa_carshop/vehicle-shop_sv.lua
> +	if currentPrice > 0 then -- If a price is set above 0 then use existing price
All good questions sir. vin scratched will still allow the pricing for it.

2022-12-26 03:50 UTC, DatBoiWeep commented on resources/usa_carshop/vehicle-shop_sv.lua
> +	if currentPrice > 0 then -- If a price is set above 0 then use existing price
I can definitely work on editing it to something else tho

2022-12-26 04:08 UTC, minipunch requested changes

2022-12-26 04:08 UTC, minipunch commented on resources/usa_carshop/vehicle-shop_sv.lua
> +		vehiclePrice = toSellVehicle.price
This is scary cause like cyber security rule #1 is don't ever trust values sent from a client when doing critical logic stuff like this

Cause someone can trigger this event with say toSellVehicle.price = 10000000000000000 and potentially exploit it that way

Which is why we are using the server sided function `GetVehiclePrice` in the first place, to 'sanitize' the input from the client and get the actual value of what the price should be based on the name or w/e the server says it should be

So how about attaching some new field like `isVinScratched` when the player gets the vehicle from that script and then here we just check `if toSellVehicle.isVinScratched then` and then do `GetVehiclePrice(toSellVehicle) * .10` (10% of the price)

2022-12-28 10:30 UTC, DatBoiWeep commented on resources/usa_carshop/vehicle-shop_sv.lua
> +		vehiclePrice = toSellVehicle.price
So looking into this and why `toSellVehicle.isVinScratched` wasn't returning a value (True/False), it seems once the vehicle is stored it just goes poof, which happens once the vehicle is VIN scratch. We gotta add the VinScratch thingy into the DB values if we want to utilize it the way you intend

2023-01-20 10:54 UTC, DatBoiWeep commented
Temporarily closing

2023-01-20 10:54 UTC, closed without merging