Fixed false anticheese flags for warehouses
minipunch/usarealismrp-fxserver pull request #1661
Opened 2022-12-25 23:45 UTC by DatBoiWeep

Fixes #1654

2022-12-26 03:33 UTC, minipunch reviewed
did u actually test this on ur test server and confirm it stopped the false alerts?

2022-12-26 03:34 UTC, DatBoiWeep commented
> did u actually test this on ur test server and confirm it stopped the false alerts?

yes, I enabled ` _anticheese` and `usa_utils` to make sure it worked

2022-12-26 03:38 UTC, minipunch commented
swagged out

2022-12-26 03:39 UTC, minipunch commented
I will say a better fix would be to automatically pull all the locations for warp points and load it that way

Otherwise any time we add or remove one we also need to update this separate list :(

2022-12-26 04:10 UTC, minipunch requested changes
see comments above, he said he will make an export to get all locations

2023-01-02 00:46 UTC, DatBoiWeep commented
**Update:** Tested, turns out we can't use a server export on a client file. So I had to use the client av-warehouse to actually make the export work.

2023-01-14 21:32 UTC, minipunch requested changes

2023-01-14 21:32 UTC, minipunch commented on resources/_anticheese/cl_anticheese.lua
> +	local warehousecoords = exports["av-warehouse"]:getWarehouseLocations()
exports are CPU intensive to call

so you should move this somewhere where it only runs one time and not every time this function is run

2023-01-14 21:32 UTC, minipunch commented on resources/av-warehouse/client/main.lua
> +		[1] = {x = coordx, y = coordy, z = coordz},
????

i don't understand this list of coordinates lol

2023-01-14 21:32 UTC, minipunch commented on resources/av-warehouse/client/main.lua
> +		[1] = {x = coordx, y = coordy, z = coordz},
shouldn't this be the actual list of locations

2023-01-20 02:16 UTC, minipunch commented on resources/av-warehouse/client/main.lua
> +		[1] = {x = coordx, y = coordy, z = coordz},
oh right this is using the set coord

maybe it would be better to grab ALL the locations at once instead here

2023-01-24 04:32 UTC, DatBoiWeep commented on resources/_anticheese/cl_anticheese.lua
> +	local warehousecoords = exports["av-warehouse"]:getWarehouseLocations()
ooooooh. Very well, I shall relocate that bad boi

2023-01-25 10:45 UTC, DatBoiWeep commented
pls re-examine. It has been tested and works

I also could not for the life of me figure out how to bring the coords from the `server.lua` to the `anticheese` client file as an export.

2023-01-26 02:34 UTC, minipunch commented
> I also could not for the life of me figure out how to bring the coords from the `server.lua` to the `anticheese` client file as an export.

just need to use `TriggerServerCallback` to fetch the info inside the get locations export

2023-01-26 02:37 UTC, minipunch commented
did it 4 u [245d266](https://github.com/minipunch/usarealismrp-fxserver/pull/1661/commits/245d2660ad53700599b9bd273e47741e5d15429a)

2023-01-26 02:56 UTC, minipunch approved these changes

2023-01-26 02:56 UTC, merged