[Drugs] Meth Levelling
minipunch/usarealismrp-fxserver pull request #1697
Opened 2023-01-16 19:16 UTC by maxgestic

Added Meth Levelling
- Ranks 1-5 with decrease in blow up chance and faster processing and packaging speeds

Closes #1526

2023-02-10 02:59 UTC, minipunch requested changes

2023-02-10 02:59 UTC, minipunch commented on resources/usa_meth/cl_meth.lua
> +            TriggerEvent("usa:notify", "Level Up! Your meth rank is now "..methRank)
Doesn't this mean this notification will be sent every single time the person loads a character with the way you have it now

2023-02-11 17:41 UTC, maxgestic commented on resources/usa_meth/cl_meth.lua
> +            TriggerEvent("usa:notify", "Level Up! Your meth rank is now "..methRank)
No thats why it checks if the client has their methRank set to nil so when they first load their char it should not send a notification

2023-02-11 17:43 UTC, maxgestic commented on resources/usa_meth/sv_meth.lua
> +TriggerEvent('es:addCommand', 'addxp', function(source, args, char, location)
no lol

2023-02-11 17:49 UTC, maxgestic commented on resources/usa_meth/sv_meth.lua
> +		TriggerEvent("interaction:addDroppedItem", methProduced)
Yea i dont think it gives it in the client file ill test it to double check but i think it was just missing cos above in "methJob:methProduced" it has the addDroppedItem if the char cant hold the item so i just added it to this one as well

2023-02-11 18:42 UTC, maxgestic commented on resources/usa_meth/sv_meth.lua
> +        db.getDocumentById("methjob", char.get("_id"), function(doc)
Done

2023-02-11 19:01 UTC, maxgestic commented on resources/usa_meth/sv_meth.lua
> +		TriggerEvent("interaction:addDroppedItem", methProduced)
Tested it and it works good

2023-02-12 04:24 UTC, minipunch approved these changes
I think we might want to increase the XP required to rank up since 1000 xp is only like 10 crafts If I am not mistaken

Might wanna make it like 20 - 30 at least so people don't climb the ranks too easily

But for now I'll merge this as is and you can do that later

2023-02-12 04:24 UTC, merged