[Police] Added Police Impound
minipunch/usarealismrp-fxserver pull request #1701
Opened 2023-01-17 02:53 UTC by maxgestic

This adds a police impound that allows BCSO and SASP officers to impound vehicles into police custody for up to 90 days. These vehicles can be retrieved by officers during this time for evidence gathering or other purposes. During this time the owner of the vehicle will not be able to retrieve their vehicles from any garage or the insurance. Police will also be able to release a vehicle early before it is meant to using `/releaseimpound [plate]`

2023-02-16 02:09 UTC, minipunch commented
Can you explain how one impounds a vehicle with this update for me plz

2023-02-16 03:25 UTC, maxgestic commented
> Can you explain how one impounds a vehicle with this update for me plz
> 
> Also FYI I am thinking 14 days to start, maybe 30 max

You just drive it to one of the impound locations and press E then enter a time you want to impound it for

2023-02-18 21:41 UTC, minipunch commented
Also with this it would be fire if we make a way for people to 'break in' and have some chance of getting their vehicle back (or failing)

2023-02-18 21:43 UTC, minipunch commented
Also it is preferable to move away from the views since it requires manual setup

There is probably a good enough way to do it using the normal DB API we have setup (i.e. `exports.essentialmode:getDocument` etc)

2023-02-25 01:51 UTC, minipunch commented on resources/usa_impound/client.lua
> +				TriggerServerEvent("usa_impound:checkCop")
Can you use `pmc-callbacks` for this instead of events please

2023-02-25 02:31 UTC, minipunch commented on resources/usa_impound/server.lua
> +	            	db.updateDocument("police-impound", "impoundedPlates", {plates = plates}, function()
In Couch DBs docs it says that for best performance keep the doc size as little as possible

So instead of appending to one giant list in a single document we should create a new, small doc for each new impounded vehicle

2023-02-25 02:35 UTC, minipunch commented on resources/usa_impound/server.lua
> +		local time_until = round((vehicle.released_on - os.time())/86400, 0)
```suggestion
		local time_until = math.floor((vehicle.released_on - os.time())/86400)
```

2023-02-25 02:35 UTC, minipunch commented on resources/usa_impound/server.lua
> +		local time_until = round((vehicle.released_on - os.time())/86400, 0)
Since it is built in

2023-02-25 02:36 UTC, minipunch commented on resources/usa_impound/server.lua
> +		TriggerClientEvent("usa:notify", usource, "Vehicle ("..vehicle.plate..") retrieved from police impound! There where "..time_until.." days left! Make sure to book it back in!", "Vehicle ("..vehicle.
```suggestion
		TriggerClientEvent("usa:notify", usource, "Vehicle ("..vehicle.plate..") retrieved from police impound! There was "..time_until.." days left! Make sure to book it back in!", "Vehicle ("..vehicle.plate..") retrieved from police impound! There where "..time_until.." days left! Make sure to book it back in!")
```

2023-02-25 02:39 UTC, minipunch commented on resources/usa_garage/server.lua
> +			local time_until = round((vehicle.released_on - os.time())/86400, 0)
```suggestion
			local time_until = math.floor((vehicle.released_on - os.time())/86400, 0)
```

built in and has no decimals

2023-02-25 02:41 UTC, minipunch commented
I impounded my vehicle but whenever I go to press E on the impound to open the menu it does not open and there aren't any errors thrown

I did update both views already

Does this not happen for you?

2023-02-25 13:20 UTC, maxgestic commented on resources/usa_impound/server.lua
> +	            	db.updateDocument("police-impound", "impoundedPlates", {plates = plates}, function()
IDK since it only stores the plate it seems a bit idk weird to make a new sheet for just storing a place, I feel like for having an array of plates it should be fine keeping it in one doc no?

2023-02-25 13:22 UTC, maxgestic commented on resources/usa_impound/server.lua
> +	            	db.updateDocument("police-impound", "impoundedPlates", {plates = plates}, function()
I mean plus having a separate sheet for each vehicle would also mean the database would be bigger overall cos if its all in one you are only storing the "_id" and "_rev" for one doc, but if you have it in separate docs then it be like multiple "_id" and "_rev"'s?

2023-02-25 13:41 UTC, maxgestic commented
> I impounded my vehicle but whenever I go to press E on the impound to open the menu it does not open and there aren't any errors thrown
> 
> I did update both views already
> 
> Does this not happen for you?

Works fine for me are you sure you where whitelisted and clocked on as a cop?
https://youtu.be/jBNtlvIfXPI

2023-02-25 13:50 UTC, maxgestic commented on resources/usa_impound/client.lua
> +				TriggerServerEvent("usa_impound:checkCop")
Changed this to use a more tradition back and forth

2023-02-25 18:40 UTC, minipunch commented
> > I impounded my vehicle but whenever I go to press E on the impound to open the menu it does not open and there aren't any errors thrown
> 
> > 
> 
> > I did update both views already
> 
> > 
> 
> > Does this not happen for you?
> 
> 
> 
> Works fine for me are you sure you where whitelisted and clocked on as a cop?
> 
> https://youtu.be/jBNtlvIfXPI

Yep I did /setjob sheriff and had rank 5, I can try again I guess..

2023-02-25 18:48 UTC, minipunch commented on resources/usa_impound/server.lua
> +	            	db.updateDocument("police-impound", "impoundedPlates", {plates = plates}, function()
It's not about the DB being larger overall, it's about trying to keep individual doc sizes as small as possible

It's fine for this application since there most likely won't be all that many impounded plates to store

But in theory if this list grew huge then reading and writing to it would be less efficient than separate docs according to the performance pages of Couch DBs documentation

Mainly because updating requires reading the entire document from disk and re-writing it all back and disk I/O is the slowest part of a DB

For example if we just want to make some very minor change to a document, then having to read all of it and write all of it back will take much longer with a large document than a small one

See the first point, "file size": https://docs.couchdb.org/en/stable/maintenance/performance.html

2023-02-26 02:13 UTC, minipunch commented on resources/usa_impound/client.lua
> +				TriggerServerEvent("usa_impound:checkCop")
Still not using `pmc-callbacks` lol

AKA:

```
local isCop = TriggerServerCallback {
  eventName = "impound:copCheck",
  args = {}
}

2023-02-26 02:16 UTC, minipunch requested changes
not using pmc callback still

2023-02-26 20:47 UTC, minipunch commented
I'll adjust it to use pmc callbacks

also prob gonna adjust how we store impounded car info to avoid having to use views and keep it isolated to a new DB

also prob gonna make it so u have to pay for every date it is stored at impound to retrieve it (like IRL lmao)

2023-02-27 04:39 UTC, minipunch approved these changes

2023-02-27 04:39 UTC, merged