[MLO] Better Vesp PD & Functionally
minipunch/usarealismrp-fxserver pull request #1712
Opened 2023-01-21 01:17 UTC by maxgestic

2023-01-21 21:03 UTC, minipunch requested changes

2023-01-21 21:03 UTC, minipunch commented on resources/usa_elevator/client.lua
> +					if IsControlJustPressed(1, 38) then
As an optimization why not wrap all of this for loop code under this if statement check

So it only runs if the person pressed the control instead of every frame all the time for no real reason

2023-01-21 21:03 UTC, minipunch commented on resources/usa_elevator/client.lua
> +LockedElevatorDoors = {
```suggestion
local LockedElevatorDoors = {
```

2023-01-21 21:03 UTC, minipunch commented on resources/usa_elevator/client.lua
> +elevatorShafts = {
```suggestion
local elevatorShafts = {
```

2023-01-21 21:14 UTC, maxgestic commented on resources/usa_elevator/client.lua
> +					if IsControlJustPressed(1, 38) then
Fixed https://github.com/minipunch/usarealismrp-fxserver/pull/1712/commits/64288eb6e056f086c469fe52a6863e6ed0744154

2023-01-21 21:28 UTC, minipunch commented
Also with this MLO (and any future additions)

Can u make sure u watch the server console log when it loads and make sure it doesn't throw any red optimization warnings for textures or something in it plz

2023-01-21 21:35 UTC, minipunch commented
Also can u move the tow clock on spot here cause it conflicts with the door lock:

![](https://i.imgur.com/7Yz22xF.jpeg)

2023-01-21 21:38 UTC, minipunch commented
Also can u make sure the menu closes when u go too far from the elevator plz:

![](https://i.imgur.com/MIVhbm5.png)

2023-01-21 21:42 UTC, minipunch commented
Also going to the 5th floor via the elevator is a bit buggy, u get stuck in here and MLO disappears: ![](https://i.imgur.com/44X3PV7.jpeg)

2023-01-21 21:58 UTC, maxgestic commented
> Also going to the 5th floor via the elevator is a bit buggy, u get stuck in here and MLO disappears: ![](https://i.imgur.com/44X3PV7.jpeg)

This is FiveM limitation because you are not entering though the portal, I am not sure how to fix this

2023-01-21 22:02 UTC, minipunch commented
> > Also going to the 5th floor via the elevator is a bit buggy, u get stuck in here and MLO disappears: ![](https://camo.githubusercontent.com/9b98a73b78b5c810ab26363e8be1f2018e4b4b61437914d0c6c1951e64898952/68747470733a2f2f692e696d6775722e636f6d2f343458335056372e6a706567)
> 
> This is FiveM limitation because you are not entering though the portal, I am not sure how to fix this

Maybe try using [`RequestLoadColl](https://docs.fivem.net/natives/?_0x07503F7948F491A7)?

If that doesn't work we should just remove the floor from the elevator options so they r forced to walk there

2023-01-22 02:45 UTC, maxgestic commented
All Above addressed in [361038c](https://github.com/minipunch/usarealismrp-fxserver/pull/1712/commits/361038c1c614d9c416f77ba5a1c2a798bf5aeaae), removed 5th floor no way to load interior

2023-01-22 02:45 UTC, maxgestic commented
Also made elevator menu go bye by eif you walk to far away

2023-01-22 02:48 UTC, minipunch approved these changes

2023-01-22 02:48 UTC, merged