update: Los Santos Lottery
minipunch/usarealismrp-fxserver pull request #1789
Opened 2023-02-10 16:30 UTC by Savage912-Official

This will allow players to buy a lottery ticket for $500 and every 14 days a winner will be auto drawn. Once the drawing has happened a chat message will be put out with the winning ticket number.

At life invader peak the desk or ped to access to lottery menu for buying ticket & claiming prize.

A player can only buy 1 ticket every 14 days. You buy 1 then once the lottery resets (Once player claims their winnings) you can then buy another for an entry in a new lottery.

2023-02-12 20:55 UTC, minipunch requested changes

2023-02-12 20:55 UTC, minipunch commented on resources/usa_lottery/client/cl_lottery.lua
> +    exports['qb-target']:AddCircleZone("lotterymenuspot", Config.TargetLocation, 2.0, {
We have qb-target? R u sure this actually works lol

2023-02-12 20:55 UTC, minipunch commented on resources/usa_lottery/shared/sh_config.lua
> +Config.TicketPrice = 500 -- Total amount the tickets cost.
We should raise this a bit to like 2000 at least I'd say, maybe even 5k

2023-02-12 20:57 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    if char.get("money") >= cost then
Can you use `char.hasEnoughMoney` or whatever it is instead

That way we can use `char.removeMoneyOrBank(amount)` so it takes from bank or cash on hand

2023-02-12 20:57 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    elseif char.get("bank") then
Then you also don't need a separate `if` statement of duplicated code if use that instead

2023-02-12 21:51 UTC, Savage912-Official commented on resources/usa_lottery/client/cl_lottery.lua
> +    exports['qb-target']:AddCircleZone("lotterymenuspot", Config.TargetLocation, 2.0, {
No but our target allows for these exports and it works.

2023-02-12 21:53 UTC, Savage912-Official commented on resources/usa_lottery/shared/sh_config.lua
> +Config.TicketPrice = 500 -- Total amount the tickets cost.
Done

2023-02-12 21:58 UTC, Savage912-Official commented on resources/usa_lottery/server/sv_lottery.lua
> +    elseif char.get("bank") then
Rone

2023-02-12 21:58 UTC, Savage912-Official commented on resources/usa_lottery/server/sv_lottery.lua
> +    if char.get("money") >= cost then
Done

2023-02-12 22:28 UTC, minipunch reviewed
Did I miss the part where it gives some % of the lottery total to the gov jobs ?

2023-02-12 22:49 UTC, minipunch commented
Also in the future please include the fact that you have to run the .sql file if it includes one plz

2023-02-12 23:02 UTC, Savage912-Official commented
> Also in the future please include the fact that you have to run the .sql file if it includes one plz
> 
> Also this is a nice thing about our setup with CouchDB rn -- you don't have to do any manual DB setup steps since it can be automated
> 
> Maybe next time u can try converting it to no sql lol
> 
> Idk why that isn't a thing for sql scripts lol

Yeah I’ll give it a go just not the best with couchdb

2023-02-12 23:41 UTC, Savage912-Official commented
> Also in the future please include the fact that you have to run the .sql file if it includes one plz
> 
> Also this is a nice thing about our setup with CouchDB rn -- you don't have to do any manual DB setup steps since it can be automated
> 
> Maybe next time u can try converting it to no sql lol
> 
> Idk why that isn't a thing for sql scripts lol

And yeah I didn’t think about saying anything about running the sql since I had said it in dms

2023-02-13 01:41 UTC, minipunch commented
Did you actually test this to make sure the winning worked?

2023-02-13 02:01 UTC, minipunch approved these changes

2023-02-13 02:01 UTC, merged