update: Lottery Percentage to Gov Accounts
minipunch/usarealismrp-fxserver pull request #1798
Opened 2023-02-13 15:16 UTC by Savage912-Official

Once the winner has been chosen half of the pot will auto be put into a random government account.

Also redid the config to look a bit cleaner than it did.

2023-02-14 02:23 UTC, minipunch requested changes

2023-02-14 02:23 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    local amount = result[1].total/2
```suggestion
    local GOV_PERCENTAGE = 0.20 -- preferably at the top of the file
    local govAmount = `GOV_PERCENTAGE * result[1].total`
    local restAmount = result[1].total - govAmount
    -- etc...
```

2023-02-14 02:23 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +        db.getDocumentById("govfunds", ident, function(doc)
```suggestion
        local doc = exports.essentialmode:getDocumentById("govfunds", ident)
```
Then get rid of the `es:exposeDBFunctions` event part

Cleaner this way

2023-02-14 02:23 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +        db.updateDocument("govfunds", fundAccount, { content = finishedBalance }, function(doc, err, rText)
```suggestion
        exports.essentialmode:updateDocument("govfunds", fundAccount, { content = finishedBalance })
```

And also get rid of the `es:exposeDBfunctions` event part

2023-02-14 02:23 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    GetCurrentBalance(fundAccount, function(bal)
Will have to update how u use the function if u do my suggestions below

2023-02-14 12:19 UTC, Savage912-Official commented on resources/usa_lottery/server/sv_lottery.lua
> +    GetCurrentBalance(fundAccount, function(bal)
Done

2023-02-16 01:49 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    local resetAmount = result[1].total - govAmount
```suggestion
    local restAmount = result[1].total - govAmount
```

2023-02-16 01:49 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    MySQL.Async.execute("UPDATE lotterytotal SET total = '"..math.floor(resetAmount).."'")
```suggestion
    MySQL.Async.execute("UPDATE lotterytotal SET total = '"..math.floor(restAmount).."'")
```

2023-02-16 01:52 UTC, minipunch requested changes

2023-02-16 01:52 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    TriggerEvent('es:exposeDBFunctions', function(db)
Don't need this when you use `exports.essentialmode...`

2023-02-16 01:52 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    TriggerEvent('es:exposeDBFunctions', function(db)
Same here

2023-02-16 19:58 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +    if doc then
Think u forgot to remove this

2023-02-16 21:01 UTC, Savage912-Official commented on resources/usa_lottery/server/sv_lottery.lua
> +    exports.essentialmode:updateDocument("govfunds", fundAccount, { content = finishedBalance })
Yeah I’ll add it

2023-02-16 23:55 UTC, Savage912-Official commented on resources/usa_lottery/server/sv_lottery.lua
> +    exports.essentialmode:updateDocument("govfunds", fundAccount, { content = finishedBalance })
I’ll get it done in the morning

2023-02-18 03:07 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +        amount = math.floor(govAmount)
```suggestion
```

not using these `amount` variables anywhere ?

2023-02-18 03:07 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +        amount = math.abs(govAmount)
```suggestion
```

2023-02-18 03:09 UTC, minipunch commented on resources/usa_lottery/server/sv_lottery.lua
> +function GetCurrentBalance(ident, cb, fundAccount)
```suggestion
function GetCurrentBalance(ident, cb)
```

not used

2023-02-18 03:12 UTC, minipunch approved these changes

2023-02-18 03:12 UTC, merged