fix: Using erp command on self
minipunch/usarealismrp-fxserver pull request #1801
Opened 2023-02-13 16:23 UTC by Savage912-Official

You can no longer use the erp command on yourself.

Issue: https://usarrp.gg/forums/topic/1410-do-not-erp-yourself/

2023-02-13 20:58 UTC, minipunch commented
![image](https://user-images.githubusercontent.com/14902187/218560992-b7975bc6-fdeb-4ef7-9fb0-5f6bf8a9c45f.jpeg)

2023-02-13 21:02 UTC, Savage912-Official commented
> ![image](https://user-images.githubusercontent.com/14902187/218560992-b7975bc6-fdeb-4ef7-9fb0-5f6bf8a9c45f.jpeg)

You can use it on yourself and it glitches you lol

2023-02-13 21:04 UTC, minipunch requested changes

2023-02-13 21:04 UTC, minipunch commented on resources/[erp]/tgiann-skillbar/server/sv_cmds.lua
> +	if not me then
```suggestion
	if source ~= id then
```

2023-02-13 21:04 UTC, minipunch commented on resources/[erp]/tgiann-skillbar/server/sv_cmds.lua
> +	if not me then
Why not do this instead and that way you don't have to use `GetPlayerPed`

I wouldn't even think it works like you have it lol

2023-02-13 21:07 UTC, Savage912-Official commented on resources/[erp]/tgiann-skillbar/server/sv_cmds.lua
> +	if not me then
It worked but yeah I’ll change

2023-02-14 01:59 UTC, minipunch approved these changes

2023-02-14 01:59 UTC, merged