update: Minimap Veh/Foot Settings
minipunch/usarealismrp-fxserver pull request #1816
Opened 2023-02-17 19:44 UTC by Savage912-Official

You can now toggle the vehicle & foot minimap on/off meaning if you have foot on but vehicle off it won't show in the vehicle etc...

2023-02-17 20:09 UTC, minipunch requested changes

2023-02-17 20:09 UTC, minipunch commented on resources/usa_hud/client.lua
> +AddEventHandler("usa_hud:ToggleMinimapVeh", function(status)
to reduce copy and pasted code which can causes problems and clutter later:

just pass in a new argument to the more generic version, so smth like: `ToggleMinimap(status, type)`

then we don't need a separate event

2023-02-17 20:09 UTC, minipunch commented on resources/usa_hud/server.lua
> +        local footenabled = false
Would be ideal to move the defaults into a common config file shared between server and client so we don't have to worry about keeping stuff synced in diff files buried in code

Like move the current `Config` object in the client script to a `shared` `config.lua` script

2023-02-17 21:23 UTC, minipunch commented on resources/usa_hud/server.lua
> +        { name = "Veh or Foot", help = "Toggle Vehicle & Foot Minimap On/Off" }
```suggestion
        { name = "type", help = "either 'veh' or 'foot'" }
```

2023-02-17 21:24 UTC, minipunch commented on resources/usa_hud/server.lua
> +        TriggerClientEvent("usa:notify", source, "Invalid Arguments Provided!")
```suggestion
        TriggerClientEvent("usa:notify", src, "Invalid Arguments Provided!")
```

2023-02-17 21:25 UTC, minipunch commented on resources/usa_hud/server.lua
> +            db.getDocumentById("minimap-settings", id, function(doc)
while we're here can you update this db stuff to use the new `exports.essentialmode...` format please since it is cleaner

2023-02-17 21:25 UTC, minipunch commented on resources/usa_hud/server.lua
> +        TriggerEvent('es:exposeDBFunctions', function(db)
don't forget here too

2023-02-17 21:27 UTC, minipunch commented on resources/usa_hud/client.lua
>  	Config.MapEnabled = TriggerServerCallback {
Looks like u forgot to update this for when they load in

2023-02-17 21:54 UTC, Savage912-Official commented on resources/usa_hud/server.lua
> +        TriggerEvent('es:exposeDBFunctions', function(db)
Alright I’ll do it in a bit

2023-02-18 02:56 UTC, minipunch commented on resources/usa_hud/client.lua
> +    enabled = Config.VehMapEnabled and Config.FootMapEnanled
![](https://i.kym-cdn.com/entries/icons/original/000/018/489/nick-young-confused-face-300x256-nqlyaa.jpg)

2023-02-18 02:57 UTC, minipunch commented on resources/usa_hud/client.lua
> +    enabled = Config.VehMapEnabled and Config.FootMapEnanled
1) "FootMapEnanled"
2) this line is overwritten by the line just after it ??

2023-02-18 02:59 UTC, minipunch commented on resources/usa_hud/server.lua
> +            exports.essentialmode:createDocumentWithId("minimap-settings", id, {footenabled = true})
No need for this separate `else` branch just to make the doc if it doesn't exist

`updateDocument` does that already since u passed `true` as the last argument already

2023-02-18 03:00 UTC, minipunch commented on resources/usa_hud/server.lua
> +            exports.essentialmode:createDocumentWithId("minimap-settings", id, {vehenabled = true})
same here

2023-02-18 03:12 UTC, minipunch commented on resources/usa_hud/server.lua
> +        if doc then
don't really need to check for whether `doc` exists either lol

2023-02-18 03:13 UTC, Savage912-Official commented on resources/usa_hud/server.lua
> +        if doc then
😂

2023-02-18 03:28 UTC, minipunch commented on resources/usa_hud/client.lua
> +				if Config.VehMapEnabled and enabled then
where does this `enabled` variable come from ??

2023-02-18 03:29 UTC, minipunch commented on resources/usa_hud/client.lua
> +				if Config.VehMapEnabled and enabled then
```suggestion
				if Config.VehMapEnabled and hud.enabled then
```

right ?

2023-02-18 05:39 UTC, minipunch commented
had some issues

for now I just did it this way:

[a8f9fe3](https://github.com/minipunch/usarealismrp-fxserver/commit/a8f9fe3780883230d792815090e40cc8a5b78937)

2023-02-18 05:39 UTC, closed without merging