Added Alpha Auto Center
minipunch/usarealismrp-fxserver pull request #1833
Opened 2023-02-21 06:35 UTC by Rezitoo

2023-02-21 18:16 UTC, minipunch commented on resources/usa_garage/client.lua
>  	{x = -181.43, y = -1289.32, z = 31.3, noBlip = true} -- Benny's
```suggestion
	{x = -181.43, y = -1289.32, z = 31.3, noBlip = true}, -- Benny's
```

u guys really just love not testing ur changes and missing commas huh

2023-02-21 18:17 UTC, minipunch requested changes
see comment

2023-02-21 18:56 UTC, Rezitoo commented
Should be good now

2023-02-22 01:27 UTC, minipunch approved these changes

2023-02-22 01:27 UTC, merged