Removed unused mlo's
minipunch/usarealismrp-fxserver pull request #1835
Opened 2023-02-21 18:36 UTC by Zeeroqt

all of these mlo's that have been removed are not used or that are fps eater

2023-02-22 01:29 UTC, minipunch commented on server.cfg
> +#ensure int_weed
Bruh 1) this is a fire interior and unless you can show me more proof that it is 'unoptimized' like the server console saying a specific file is too large or smth then let's keep this for now

and 2) if we did want to remove it it has a weed process location we'd need to remove also

2023-02-22 01:30 UTC, minipunch commented on server.cfg
> +#start map_fightclub
there is a map blip here that u should remove if u remove this

2023-02-22 01:30 UTC, minipunch requested changes
see comments

2023-02-22 01:39 UTC, Zeeroqt commented on server.cfg
> +#start map_fightclub
yeah pushing now

2023-02-22 01:39 UTC, Zeeroqt commented on server.cfg
> +#ensure int_weed
it is in the smack middle of legion which there are 4 different mlo's in legion. which can cause it to have a drop of frames. I can remove it from the fire script and the weed process also.

2023-02-22 01:39 UTC, Zeeroqt commented on server.cfg
> +#start map_fightclub
https://github.com/minipunch/usarealismrp-fxserver/pull/1839/commits/2f3322457fec4e674fc68a7b12d2feabab59846c done

2023-02-22 13:04 UTC, Zeeroqt commented
i dont i can just make them in the same pr because when i do it on github desktop it includes my server key, steam api key, and other stuff. unless there is a way i can just add it to this one

2023-02-23 02:58 UTC, minipunch commented
> i dont i can just make them in the same pr because when i do it on github desktop it includes my server key, steam api key, and other stuff. unless there is a way i can just add it to this one

![](https://i.kym-cdn.com/entries/icons/mobile/000/018/489/nick-young-confused-face-300x256-nqlyaa.jpg)

2023-02-23 03:02 UTC, Zeeroqt commented
> ****
> [ Resolve conflicts ](/minipunch/usarealismrp-fxserver/pull/1835/conflicts)

i cant in the same pr when i do the changes it will list my server key, my steam web api key, and more. So i had to edit the server.cfg on github through browser. Unless u can merge 2 things in the same PR through github online too.

2023-02-23 03:03 UTC, Zeeroqt commented
> > [ Resolve conflicts ](/minipunch/usarealismrp-fxserver/pull/1835/conflicts)
> 
> i cant in the same pr when i do the changes it will list my server key, my steam web api key, and more. So i had to edit the server.cfg on github through browser. Unless u can merge 2 things in the same PR through github online too.

i mean i cant have it in the same pr on github bc it leaks the stuff i stated above

2023-02-23 03:03 UTC, minipunch commented
> > > [ Resolve conflicts ](/minipunch/usarealismrp-fxserver/pull/1835/conflicts)
> > 
> > 
> > i cant in the same pr when i do the changes it will list my server key, my steam web api key, and more. So i had to edit the server.cfg on github through browser. Unless u can merge 2 things in the same PR through github online too.
> 
> i mean i cant have it in the same pr on github bc it leaks the stuff i stated above

but I'm saying u should be able to without leaking anything lol

2023-02-23 03:06 UTC, Zeeroqt commented
> > > > [ Resolve conflicts ](/minipunch/usarealismrp-fxserver/pull/1835/conflicts)
> > > 
> > > 
> > > i cant in the same pr when i do the changes it will list my server key, my steam web api key, and more. So i had to edit the server.cfg on github through browser. Unless u can merge 2 things in the same PR through github online too.
> > 
> > 
> > i mean i cant have it in the same pr on github bc it leaks the stuff i stated above
> 
> but I'm saying u should be able to without leaking anything lol

it says +sv_licensekey" then my key" imma edit it on github and then put stuff back after

2023-02-23 03:11 UTC, minipunch commented
> > > > > [ Resolve conflicts ](/minipunch/usarealismrp-fxserver/pull/1835/conflicts)
> > > > 
> > > > 
> > > > i cant in the same pr when i do the changes it will list my server key, my steam web api key, and more. So i had to edit the server.cfg on github through browser. Unless u can merge 2 things in the same PR through github online too.
> > > 
> > > 
> > > i mean i cant have it in the same pr on github bc it leaks the stuff i stated above
> > 
> > 
> > but I'm saying u should be able to without leaking anything lol
> 
> it says +sv_licensekey" then my key" imma edit it on github desktop by deleting my stuff and adding it back

Sounds like you skipped the `server_internal.cfg` file part of the readme 😂

2023-02-23 03:23 UTC, Zeeroqt commented
ok new pr done

2023-02-23 03:24 UTC, Zeeroqt commented
> > > > > > [ Resolve conflicts ](/minipunch/usarealismrp-fxserver/pull/1835/conflicts)
> > > > > 
> > > > > 
> > > > > i cant in the same pr when i do the changes it will list my server key, my steam web api key, and more. So i had to edit the server.cfg on github through browser. Unless u can merge 2 things in the same PR through github online too.
> > > > 
> > > > 
> > > > i mean i cant have it in the same pr on github bc it leaks the stuff i stated above
> > > 
> > > 
> > > but I'm saying u should be able to without leaking anything lol
> > 
> > 
> > it says +sv_licensekey" then my key" imma edit it on github desktop by deleting my stuff and adding it back
> 
> Sounds like you skipped the `server_internal.cfg` file part of the readme 😂

closing this in 5 min

2023-02-23 16:01 UTC, closed without merging