Slash Tires
minipunch/usarealismrp-fxserver pull request #1980
Opened 2023-03-27 05:43 UTC by Rezitoo

Added the ability for players to use Sharp Objects to Slash vehicle tires, but watch out there is a chance 911 gets a call!

Uses third eye to slash tire
Chance of missing
911 Call

2023-03-27 05:43 UTC, Rezitoo commented
https://i.imgur.com/kuC6OGT.png

2023-03-27 12:32 UTC, Savage912-Official commented
Nice!

2023-04-02 18:10 UTC, minipunch commented
Well first attempt didn't go so well...

![](https://i.imgur.com/uciVYHn.png)

2023-04-02 18:12 UTC, minipunch commented
Not sure if this is cause of your script though cause it just happened again without event trying.. all I did was open F8

2023-04-02 18:16 UTC, minipunch commented
Don't think u have to worry about that stuff, think that is a FiveM issue

but you did forget to start `slashtires` in `server.cfg`

2023-04-02 18:19 UTC, minipunch commented
Also like you mentioned this removes the `TAB` to put away weapon hotkey

We should indeed fix that so that still works

What was the reason for that here??

2023-04-02 19:24 UTC, minipunch requested changes

2023-04-02 19:24 UTC, minipunch commented on resources/interaction-menu/cl_thirdEye.lua
> -function onATMInteract(targetData, itemData)
Looks like you merged incorrectly here

We need these functions (this is stuff added not long ago)

2023-04-02 19:24 UTC, minipunch commented on resources/interaction-menu/cl_thirdEye.lua
> +        for name, index in pairs(bones) do
Where is `bones` defined here?

2023-04-02 19:24 UTC, minipunch commented on resources/interaction-menu/cl_thirdEye.lua
> -function addCivModelOptions()
again lost stuff

2023-04-02 19:24 UTC, minipunch commented on resources/interaction-menu/inventory/hotkeys/cl_hotkeys.lua
> +                    if IsDisabledControlJustPressed(24, KEYS.CTRL) then
Why change this ?

2023-04-02 21:59 UTC, Rezitoo commented
> Also like you mentioned this removes the `TAB` to put away weapon hotkey
> 
> 
> 
> We should indeed fix that so that still works
> 
> 
> 
> What was the reason for that here??

So the script requires the weapon to be in hand to actually slash the tire and with pressing tab to open the third eye to begin to slash the tire would in turn put the weapon away making slashing the tire impossible

2023-04-02 23:05 UTC, Rezitoo commented on resources/interaction-menu/cl_thirdEye.lua
> +        for name, index in pairs(bones) do
Bones are defined at the beginning of the script https://i.imgur.com/zjr8Wlr.png

2023-04-02 23:06 UTC, Rezitoo commented on resources/interaction-menu/cl_thirdEye.lua
> -function onATMInteract(targetData, itemData)
Will get it added

2023-04-02 23:06 UTC, Rezitoo commented on resources/interaction-menu/cl_thirdEye.lua
> -function addCivModelOptions()
Will get it added

2023-04-02 23:07 UTC, Rezitoo commented on resources/interaction-menu/inventory/hotkeys/cl_hotkeys.lua
> +                    if IsDisabledControlJustPressed(24, KEYS.CTRL) then
This was my attempt to change the key to put away the weapon, Is what enabled the script to work with the third eye in the first place

2023-04-04 10:18 UTC, DatBoiWeep commented on resources/interaction-menu/cl_thirdEye.lua
> -function onATMInteract(targetData, itemData)
should be back now

2023-04-04 10:18 UTC, DatBoiWeep commented on resources/interaction-menu/cl_thirdEye.lua
> -function addCivModelOptions()
should be back now

2023-04-26 02:34 UTC, Savage912-Official commented
> > > Also like you mentioned this removes the `TAB` to put away weapon hotkey
> > > We should indeed fix that so that still works
> > > What was the reason for that here??
> > 
> > 
> > So the script requires the weapon to be in hand to actually slash the tire and with pressing tab to open the third eye to begin to slash the tire would in turn put the weapon away making slashing the tire impossible
> 
> To avoid changing the third eye hotkey we should just give the player a knife (if they have one in their inv) before we call the slash tire event and it ought to work then right

We

> > > Also like you mentioned this removes the `TAB` to put away weapon hotkey
> > > We should indeed fix that so that still works
> > > What was the reason for that here??
> > 
> > 
> > So the script requires the weapon to be in hand to actually slash the tire and with pressing tab to open the third eye to begin to slash the tire would in turn put the weapon away making slashing the tire impossible
> 
> To avoid changing the third eye hotkey we should just give the player a knife (if they have one in their inv) before we call the slash tire event and it ought to work then right

Yeah that would work

2023-04-26 04:19 UTC, minipunch approved these changes

2023-04-26 04:19 UTC, merged