New Oxy Script
minipunch/usarealismrp-fxserver pull request #2017
Opened 2023-04-11 03:58 UTC by Zeeroqt

- Buffed Drug Sale Prices
- Added Oxy to drug selling
- Added a chance of getting oxy in robbing houses
- Added a Big Reward Chance
- Added the ability to sell the Big Reward
- Added Oxy as a Healing Item
- Added consuming pill animation 
- Added Overall Oxy Script

2023-04-12 20:47 UTC, minipunch commented
Can you explain a bit how it works for me please

2023-04-12 20:51 UTC, Zeeroqt commented
> Can you explain a bit how it works for me please

Yeah so basically u go up to a local and u have to pay a fee to start this mission. U get a vehicle to start doing these oxy runs. After 30 seconds to a minute u while receive a blip on ur map to go to. After going to the location there will be a ped that spawns in and basically do a trade deal with an animation. U can mainly get money but have a 25% chance getting oxy. And u have a 3.5 chance of getting a rare painting that can sell for $$$

2023-04-13 19:13 UTC, Zeeroqt commented
Could u show a clip of it giving u a medkit animation. It shouldn’t, it tested it out and only got the pill animation

2023-04-13 19:15 UTC, Zeeroqt commented
It takes 35 seconds to get the full 70 health from it. Remember u only get a % chance of getting it. U don’t just get it every run.

2023-04-13 19:43 UTC, ChangyBoi commented
This was tested when you first made the PR and I don't have a clip

Theres no medkit animation its just the pill animation

The way we saw it was, Chris got low hp, pop the oxy, health starts to regen and after a couple of seconds, it will boost your health in one big swoop. If that makes sense lol

2023-04-13 23:14 UTC, Zeeroqt commented
🤔

2023-04-15 07:19 UTC, DatBoiWeep requested changes
Double check the healing. Either lower the initial healing or remove the part during the animation imo.

2023-04-18 01:07 UTC, Zeeroqt commented on resources/interaction-menu/cl_interaction.lua
> +        SetEntityHealth(PlayerPedId(), GetEntityHealth(PlayerPedId()) + 1)
hmm ok thanks

2023-04-18 01:13 UTC, Zeeroqt commented
@minipunch lookin good?

2023-04-22 23:22 UTC, Zeeroqt commented on resources/interaction-menu/cl_interaction.lua
> +        SetEntityHealth(PlayerPedId(), GetEntityHealth(PlayerPedId()) + 1)
fixed forgot to respond to

2023-05-22 23:43 UTC, minipunch commented
Can u upload a video of how to do it so I can test it

and fix the merge conflict plz

2023-06-20 16:45 UTC, closed without merging