update: Event Planners Temp Blips CMD
minipunch/usarealismrp-fxserver pull request #2089
Opened 2023-05-04 19:46 UTC by Savage912-Official

Temporary Blips for event planners.

closes #601

Previews:
![image](https://user-images.githubusercontent.com/55938321/236316193-16daaa28-12bb-4816-96af-21a96f676ed1.png)
![image](https://user-images.githubusercontent.com/55938321/236316217-3ea22016-a191-4066-a73a-bb31c71da6ec.png)

2023-05-24 17:35 UTC, minipunch commented
Does this work even if the player relogs?

2023-05-26 18:57 UTC, Savage912-Official commented
> Does this work even if the player relogs?
> 
> If not, then u might want to move more of the logic to the server side so it can handle syncing when player's load in and what not better

True I’ll work on it Monday

2023-06-01 09:25 UTC, K7AKEN commented
@Savage912-Official asked me to work on this for him, Is there any other way to commit my changes? as it blocks me from doing so, should I put it in another pr, or comment it below?

2023-06-01 13:49 UTC, Savage912-Official commented
> @Savage912-Official asked me to work on this for him, Is there any other way to commit my changes? as it blocks me from doing so, should I put it in another pr, or comment it below?

Added you as a contributor on my repo

2023-06-01 16:11 UTC, minipunch commented
FYI I saw there were changes committed by @K7AKEN but it tells me this about them:

> "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

So If those changes were made to K7's fork of the repo then u need to make a PR from there to Savage's fork (with the same branch as this PR) and then it should show up here

2023-06-01 17:11 UTC, K7AKEN commented
> FYI I saw there were changes committed by @K7AKEN but it tells me this about them:
> 
> > "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."
> 
> So If those changes were made to K7's fork of the repo then u need to make a PR from there to Savage's fork (with the same branch as this PR) and then it should show up here

That's weird because they show up on his branch/fork as well, I'll check it out more when I get home.

2023-06-01 22:28 UTC, minipunch commented
> > FYI I saw there were changes committed by @K7AKEN but it tells me this about them:
> > > "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."
> > 
> > 
> > So If those changes were made to K7's fork of the repo then u need to make a PR from there to Savage's fork (with the same branch as this PR) and then it should show up here
> 
> That's weird because they show up on his branch/fork as well, I'll check it out more when I get home.

Hm wait I think it did apply the changes here actually judging by the commit history so nevermind that 👌

2023-06-20 01:57 UTC, Savage912-Official commented
Any updates?

2023-06-20 03:18 UTC, minipunch commented
Gonna try it soon

2023-06-20 17:02 UTC, minipunch requested changes
See comments below + also I relogged and the blip I placed still went away

2023-06-22 00:20 UTC, minipunch commented
Did u make sure the blip didn't go away when u relogged? Cause it does for me as I stated above @K7AKEN

2023-06-29 18:15 UTC, Savage912-Official commented
Gonna start working on it in a bit

2023-06-29 19:02 UTC, Savage912-Official commented on resources/usa_eventPlanners/cl_eventPlanners.lua
> +        {type = 'input', label = 'Icon', description = 'Icon of the blip (Reference list you were given.)'},
I was thinking we could put the link in event planners chat for it so people could grab it from there.

2023-06-29 19:06 UTC, Savage912-Official commented on resources/usa_eventPlanners/cl_eventPlanners.lua
> +        {type = 'input', label = 'Coordinates', description = 'Format: x, y, z'},
Done

2023-06-29 19:12 UTC, Savage912-Official commented
> Did u make sure the blip didn't go away when u relogged? Cause it does for me as I stated above @K7AKEN

I just tested and the blip stayed when I relogged.

2023-06-29 19:55 UTC, K7AKEN commented
> > Did u make sure the blip didn't go away when u relogged? Cause it does for me as I stated above @K7AKEN
> 
> I just tested and the blip stayed when I relogged.

Same here, it worked perfectly for me. Only thing is that it says blip even if there isn't one. And the blip list you mentioned

2023-10-16 06:38 UTC, minipunch approved these changes

2023-10-16 06:39 UTC, minipunch commented
Nice, it does seem to work actually, good stuff!

2023-10-16 06:39 UTC, merged