Add more staff logs
minipunch/usarealismrp-fxserver pull request #2126
Opened 2023-05-25 02:03 UTC by DatBoiWeep

2023-05-29 20:27 UTC, minipunch commented on resources/erp_adminmenu/client/client.lua
> +      if alert and not Cloack then
```suggestion
      if alert and not Cloak then
```

2023-05-29 20:27 UTC, minipunch commented on resources/erp_adminmenu/client/client.lua
> +      if not alert then
```suggestion
      if not alerted then
```

2023-05-29 20:29 UTC, minipunch commented on resources/erp_adminmenu/server/server.lua
> +	Wait(150) -- To avoid display in text-chat
???

2023-05-29 20:29 UTC, minipunch commented on resources/erp_adminmenu/client/client.lua
> +  -- NotifyStaff(PlayerId(), 'has started/stopped NoClip command.')
```suggestion
```

Can u plz remove these comments if not useful

2023-05-29 20:30 UTC, minipunch requested changes
see comments

2023-05-29 20:40 UTC, DatBoiWeep commented on resources/erp_adminmenu/server/server.lua
> +	Wait(150) -- To avoid display in text-chat
If I take it off. It shows up on the text chat like this 💀 

![image](https://github.com/minipunch/usarealismrp-fxserver/assets/27328529/9747a281-2434-43b1-8be7-791ed613da14)

2023-05-29 23:24 UTC, minipunch commented on resources/erp_adminmenu/server/server.lua
> +	Wait(150) -- To avoid display in text-chat
You mean the coloring? You can fix that by prefixing the string with `^0` to make it white for example

2023-06-03 19:15 UTC, minipunch approved these changes

2023-06-03 19:15 UTC, merged