Toggleclothing update
minipunch/usarealismrp-fxserver pull request #841
Opened 2022-05-03 06:47 UTC by DatBoiWeep

Should be good for both mp male and female ped models :)

2022-05-05 02:49 UTC, minipunch commented
No need to copy the events and rename them like you did though

Just use the existing component events @DatBoiWeep

2022-05-05 02:52 UTC, minipunch requested changes
see the comment I left

2022-05-05 02:52 UTC, DatBoiWeep commented
> No need to copy and paste the events and rename them like you did
> 
> 
> 
> Just use the existing component events but with the new numbers @DatBoiWeep 

Oooooh okay. Bet. I'll do that and also add the /bag command too while I'm at

2022-05-05 08:08 UTC, DatBoiWeep commented
Should be good now :)

2022-05-07 03:26 UTC, minipunch requested changes
`/mask` seems broken :bruh:

2022-05-07 04:55 UTC, DatBoiWeep commented
I fixed it. Pls review /e peeposhy

2022-05-07 22:22 UTC, minipunch approved these changes

2022-05-07 22:22 UTC, minipunch commented on resources/usa_toggleclothes/cl_toggleclothing.lua
> +			local value = GetPedDrawableVariation(ped, component_index)
Would be ideal to not have so much code being copy and pasted around for cleanliness purposes

But I'll merge this for now since it works and perhaps in the future some of the duplicated code can be put into a shared function

2022-05-07 22:22 UTC, merged