fixed scissors and pistol extended mag images
minipunch/usarealismrp-fxserver pull request #865
Opened 2022-05-09 22:32 UTC by DatBoiWeep

safety scissors :)

2022-05-10 01:16 UTC, minipunch requested changes

2022-05-10 01:16 UTC, minipunch commented on resources/interaction-menu/ui/js/script.js
>      "Empty Pistol Extended Mag": "https://i.imgur.com/3m72QvM.png",
Can you test if it still works if you just delete the `Empty Pistol Extended Mag` and `Loaded Pistol Extended Mag` all together and just keep `Pistol Extended Mag` for me please?

And then same for the SMG Drum Mag

2022-05-10 06:09 UTC, DatBoiWeep commented on resources/interaction-menu/ui/js/script.js
>      "Empty Pistol Extended Mag": "https://i.imgur.com/3m72QvM.png",
After removing them, turns out they are no longer needed. Same for the drum mags

2022-05-11 00:52 UTC, minipunch approved these changes

2022-05-11 00:52 UTC, merged