outlaw MC update
minipunch/usarealismrp-fxserver pull request #907
Opened 2022-05-16 06:38 UTC by ChangyBoi

Added bar & auto repair at outlaw biker spot

2022-05-16 19:15 UTC, minipunch commented on resources/usa_autorepair/cl_autorepair.lua
>  	{58.345020294189, 2789.1938476562, 56.891422271729} -- harmony
You missed a comma at the end of the previous item

This would break the script merging it like this

Plz fix

2022-05-16 19:15 UTC, minipunch commented on resources/usa_bars/cl_bars.lua
>      {x = -1293.1474609375, y = -297.61184692383, z = 36.050827026367} -- arcade
Same here

2022-05-16 19:15 UTC, minipunch requested changes
see comments

2022-05-17 01:40 UTC, ChangyBoi commented
Should be fixed now

2022-05-17 03:18 UTC, minipunch approved these changes

2022-05-17 03:18 UTC, merged