Change(Guns): Weapon Changes
minipunch/usarealismrp-fxserver pull request #910
Opened 2022-05-16 20:32 UTC by Savage912-Official

- Removed Screen Shake When Shooting
- Removed Recoil When Shooting
- Removed Some Old Weapons

- Added New Guns
- Weapons Now Have Bullet Spread When Shooting Rather Than Recoil (May add a little recoil back)

New Guns:
- AK-47
- Beretta M9A3
- Desert Eagle
- Glock
- Glock 18C (AP Pistol)
- M4 Rifle
- Sig Sauer P226R
- Remington 870
- Uzi

I do plan to add more weapons in the future just wanted to see how these do for now to see how everything goes with them in the server.

2022-05-16 20:33 UTC, Crownapple commented
+1 ME LIKE

2022-05-16 20:59 UTC, minipunch commented
1) > "Removed Some Old Weapons"

What were the 'old weapons' ?

and 2) does the 'bullet spread' still work when shooting from within a vehicle also?

2022-05-16 20:59 UTC, minipunch commented on resources/usa_ammunition/server/sv_ammunition.lua
> +    [[--[GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = {
```suggestion
    [[--[[GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = {
```
isn't it supposed to be like that instead for a comment

2022-05-16 21:20 UTC, Savage912-Official commented on resources/usa_ammunition/server/sv_ammunition.lua
> +    [[--[GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = {
Yeah it looks weird on github but its because I commented out multiple lines. 

Also when I say "Old Weapons" I mean I just commented out the weapons that weren't replaced with custom models until I could get them replaced with custom models and metas.

2022-05-16 21:21 UTC, Savage912-Official commented
> 2\. f

Regarding the bullet spread when shooting it should and the _weaponrealism script also makes weapons a bit more inaccurate while shooting from vehicles. I still do have a bit of recoil on the weapons as well.

2022-05-16 21:22 UTC, Savage912-Official commented on resources/usa_ammunition/server/sv_ammunition.lua
> +    [[--[GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = {
Also no the way I commented it out was correct.

2022-05-16 21:26 UTC, minipunch commented on resources/usa_ammunition/server/sv_ammunition.lua
> +    [[--[GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = {
> "I just commented out the weapons that weren't replaced with custom models until I could get them replaced with custom models and metas."

And why not just leave them in ?

2022-05-16 21:28 UTC, minipunch commented on resources/_weaponrealism/cl_weapon-realism.lua
>  local RECOILS = {
If our intention is to disable the recoil completely here; instead of replacing all of the existing values with 0 can you just make some constant that will act as a toggle variable to turn it on and off. That way we can easily go back without having to search through git history if we wanted.

2022-05-16 21:29 UTC, Savage912-Official commented on resources/usa_ammunition/server/sv_ammunition.lua
> +    [[--[GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = {
We can. I'll change quickly

2022-05-16 21:29 UTC, minipunch requested changes
see last comment

2022-05-16 21:39 UTC, Savage912-Official commented on resources/_weaponrealism/cl_weapon-realism.lua
>  local RECOILS = {
Yeah I can look into that.

2022-05-17 05:05 UTC, ChangyBoi commented
in the gun-shop_sv.Lua, you re-enabled stun gun, marksman pistol, and revolver. Those are to be left commented out. Whatever is left in the server of those will be what is left

2022-05-17 10:15 UTC, Savage912-Official commented
> in the gun-shop_sv.Lua, you re-enabled stun gun, marksman pistol, and revolver. Those are to be left commented out. Whatever is left in the server of those will be what is left
> 
> Also your meta files might go and conflict with the ones in gunmetas. If needed you can remove everything in there but leave the weaponanimations.meta since it controls the rate of fire

Fixed

2022-05-17 11:02 UTC, Savage912-Official commented
> see last comment

Everything is sorted now

2022-05-17 23:01 UTC, Savage912-Official commented
Gonne redo later without custom models and just with bullet spread and lower recoil.

2022-05-17 23:01 UTC, closed without merging