Vehicle damage script
minipunch/usarealismrp-fxserver pull request #917
Opened 2022-05-18 03:55 UTC by Urbaniized

Video takes too long to process and upload but I can show you in a live stream

Made sure that it doesn't affect any current systems.

Vehicle gets repairs at LS customs and repair shops
Vehicle stays orange if put in garage (doesn't reset engine health)
Mechanic repair kits work and count towards repairs for successful repairs

2022-05-18 14:28 UTC, Urbaniized commented
forgot to add the new server CFG

just do `ensure usa_seatbelt`

2022-05-25 05:49 UTC, minipunch commented
I'm confused

Why is there a new `usa_seatbelt` resource and why has it not been mentioned ??

You've only mentioned there is a new vehicle damage script which I assume is what the changes to usa_vehdamage is

2022-05-25 05:50 UTC, minipunch reviewed
see comments

2022-05-26 00:31 UTC, Urbaniized commented
The current one basically starts you at 100 health then moves to 50 health then 0 health.

This one work by slowly going from 100-0. If you hit a stop sign, it will damage the engine but it won't instantly go to 50 health. The harder you drive the car with a damaged engine the faster the engine degrades.

https://github.com/StockholmCityRP/fivem-realisticvehicle

It was the only one I could find that will work with the current framework. Also it is highly customizable vs what we have right now.

2022-05-26 02:26 UTC, minipunch requested changes

2022-05-26 02:26 UTC, minipunch commented on resources/usa_vehdamage/config.lua
> +	damageFactorEngine = 1.0,					-- Sane values are 1 to 100. Higher values means more damage to vehicle. A good starting point is 10
```suggestion
	damageFactorEngine = 2.0,					-- Sane values are 1 to 100. Higher values means more damage to vehicle. A good starting point is 10

```

2022-05-26 02:26 UTC, minipunch commented on resources/usa_vehdamage/config.lua
> +	damageFactorBody = 1.5,						-- Sane values are 1 to 100. Higher values means more damage to vehicle. A good starting point is 10
```suggestion
	damageFactorBody = 2.5,						-- Sane values are 1 to 100. Higher values means more damage to vehicle. A good starting point is 10

```

2022-05-26 02:27 UTC, minipunch approved these changes

2022-05-26 02:27 UTC, merged